const IMAGES: Record<string, string> = {
  apl: 'apple',
  avo: 'avocado',
  bcn: 'bacon',
  bnn: 'banana',
  bsl: 'basil',
  chs: 'cheese',
  chtom: 'cherrytomatoes',
  chrz: 'chorizo',
  cuc: 'cucumber',
  egg: 'egg',
  ff: 'friedfillet',
  bpgrn: 'greenbellpepper',
  ham: 'ham',
  brgr: 'hamburger',
  hssg: 'herbedsausage',
  jpno: 'jalapeno',
  kw: 'kiwi',
  kstk: 'klawfstick',
  let: 'lettuce',
  ndls: 'noodles',
  onn: 'onion',
  pkl: 'pickle',
  pnpl: 'pineapple',
  ptsld: 'potatosalad',
  pttor: 'potatotortilla',
  pro: 'prosciutto',
  bpred: 'redbellpepper',
  ronn: 'redonion',
  rice: 'rice',
  smf: 'smokedfillet',
  straw: 'strawberry',
  tofu: 'tofu',
  tom: 'tomato',
  wcrs: 'watercress',
  bpylw: 'yellowbellpepper',
  but: 'butter',
  chili: 'chilisauce',
  crmch: 'creamcheese',
  curry: 'currypowder',
  hrdsh: 'horseradish',
  jam: 'jam',
  ktchp: 'ketchup',
  mmld: 'marmalade',
  mayo: 'mayonnaise',
  mstrd: 'mustard',
  oil: 'oliveoil',
  pbtr: 'peanutbutter',
  pep: 'pepper',
  salt: 'salt',
  vngr: 'vinegar',
  wsbi: 'wasabi',
  whcrm: 'whippedcream',
  ygrt: 'yogurt',
  hmbtr: 'bitterherbamystica',
  hmspc: 'spicyherbamystica',
  hmslt: 'saltyherbamystica',
  hmsr: 'sourherbamystica',
  hmswt: 'sweetherbamystica',
  hmany: 'anyherbamystica',
};

const NAMES: Record<string, string> = {
  apl: 'Apple',
  avo: 'Avocado',
  bcn: 'Bacon',
  bnn: 'Banana',
  bsl: 'Basil',
  chs: 'Cheese',
  chtom: 'Cherry Tomatoes',
  chrz: 'Chorizo',
  cuc: 'Cucumber',
  egg: 'Egg',
  ff: 'Fried Fillet',
  bpgrn: 'Green Bell Pepper',
  ham: 'Ham',
  brgr: 'Hamburger',
  hssg: 'Herbed Sausage',
  jpno: 'Jalapeño',
  kw: 'Kiwi',
  kstk: 'Klawf Stick',
  let: 'Lettuce',
  ndls: 'Noodles',
  onn: 'Onion',
  pkl: 'Pickle',
  pnpl: 'Pineapple',
  ptsld: 'Potato Salad',
  pttor: 'Potato Tortilla',
  pro: 'Prosciutto',
  bpred: 'Red Bell Pepper',
  ronn: 'Red Onion',
  rice: 'Rice',
  smf: 'Smoked Fillet',
  straw: 'Strawberry',
  tofu: 'Tofu',
  tom: 'Tomato',
  wcrs: 'Watercress',
  bpylw: 'Yellow Bell Pepper',
  but: 'Butter',
  chili: 'Chili Sauce',
  crmch: 'Cream Cheese',
  curry: 'Curry Powder',
  hrdsh: 'Horseradish',
  jam: 'Jam',
  ktchp: 'Ketchup',
  mmld: 'Marmalade',
  mayo: 'Mayonnaise',
  mstrd: 'Mustard',
  oil: 'Olive Oil',
  pbtr: 'Peanut Butter',
  pep: 'Pepper',
  salt: 'Salt',
  vngr: 'Vinegar',
  wsbi: 'Wasabi',
  whcrm: 'Whipped Cream',
  ygrt: 'Yogurt',
  hmbtr: 'Bitter Herba Mystica',
  hmspc: 'Spicy Herba Mystica',
  hmslt: 'Salty Herba Mystica',
  hmsr: 'Sour Herba Mystica',
  hmswt: 'Sweet Herba Mystica',
  hmany: 'Herba Mystica',
};

export const ingredientName = (id: string): string => NAMES[id] ?? id;

export const ingredientImageSrc = (id: string): string | null => {
  const file = IMAGES[id];
  return file ? `/assets/ingredient/${file}.png` : null;
};
