import type { CosmeticFormConfig } from "./cosmetic-forms";

// HOME-visible battle forms sourced from PokeAPI pokemon names.
// These are tracked as cosmetic forms so they appear when the Forms toggle is on.
export const HOME_BATTLE_FORMS: CosmeticFormConfig[] = [
  { speciesId: 460, apiName: "abomasnow-mega", displayName: "Abomasnow Mega", label: "Mega" },
  { speciesId: 359, apiName: "absol-mega", displayName: "Absol Mega", label: "Mega" },
  { speciesId: 359, apiName: "absol-mega-z", displayName: "Absol Mega Z", label: "Mega Z" },
  { speciesId: 142, apiName: "aerodactyl-mega", displayName: "Aerodactyl Mega", label: "Mega" },
  { speciesId: 306, apiName: "aggron-mega", displayName: "Aggron Mega", label: "Mega" },
  { speciesId: 65, apiName: "alakazam-mega", displayName: "Alakazam Mega", label: "Mega" },
  { speciesId: 869, apiName: "alcremie-gmax", displayName: "Alcremie G-Max", label: "G-Max" },
  { speciesId: 334, apiName: "altaria-mega", displayName: "Altaria Mega", label: "Mega" },
  { speciesId: 181, apiName: "ampharos-mega", displayName: "Ampharos Mega", label: "Mega" },
  { speciesId: 842, apiName: "appletun-gmax", displayName: "Appletun G-Max", label: "G-Max" },
  { speciesId: 531, apiName: "audino-mega", displayName: "Audino Mega", label: "Mega" },
  { speciesId: 354, apiName: "banette-mega", displayName: "Banette Mega", label: "Mega" },
  { speciesId: 689, apiName: "barbaracle-mega", displayName: "Barbaracle Mega", label: "Mega" },
  { speciesId: 998, apiName: "baxcalibur-mega", displayName: "Baxcalibur Mega", label: "Mega" },
  { speciesId: 15, apiName: "beedrill-mega", displayName: "Beedrill Mega", label: "Mega" },
  { speciesId: 9, apiName: "blastoise-gmax", displayName: "Blastoise G-Max", label: "G-Max" },
  { speciesId: 9, apiName: "blastoise-mega", displayName: "Blastoise Mega", label: "Mega" },
  { speciesId: 257, apiName: "blaziken-mega", displayName: "Blaziken Mega", label: "Mega" },
  { speciesId: 12, apiName: "butterfree-gmax", displayName: "Butterfree G-Max", label: "G-Max" },
  { speciesId: 323, apiName: "camerupt-mega", displayName: "Camerupt Mega", label: "Mega" },
  { speciesId: 851, apiName: "centiskorch-gmax", displayName: "Centiskorch G-Max", label: "G-Max" },
  { speciesId: 609, apiName: "chandelure-mega", displayName: "Chandelure Mega", label: "Mega" },
  { speciesId: 6, apiName: "charizard-gmax", displayName: "Charizard G-Max", label: "G-Max" },
  { speciesId: 6, apiName: "charizard-mega-x", displayName: "Charizard Mega X", label: "Mega X" },
  { speciesId: 6, apiName: "charizard-mega-y", displayName: "Charizard Mega Y", label: "Mega Y" },
  { speciesId: 652, apiName: "chesnaught-mega", displayName: "Chesnaught Mega", label: "Mega" },
  { speciesId: 358, apiName: "chimecho-mega", displayName: "Chimecho Mega", label: "Mega" },
  { speciesId: 815, apiName: "cinderace-gmax", displayName: "Cinderace G-Max", label: "G-Max" },
  { speciesId: 36, apiName: "clefable-mega", displayName: "Clefable Mega", label: "Mega" },
  { speciesId: 839, apiName: "coalossal-gmax", displayName: "Coalossal G-Max", label: "G-Max" },
  { speciesId: 879, apiName: "copperajah-gmax", displayName: "Copperajah G-Max", label: "G-Max" },
  { speciesId: 823, apiName: "corviknight-gmax", displayName: "Corviknight G-Max", label: "G-Max" },
  { speciesId: 740, apiName: "crabominable-mega", displayName: "Crabominable Mega", label: "Mega" },
  { speciesId: 491, apiName: "darkrai-mega", displayName: "Darkrai Mega", label: "Mega" },
  { speciesId: 655, apiName: "delphox-mega", displayName: "Delphox Mega", label: "Mega" },
  { speciesId: 719, apiName: "diancie-mega", displayName: "Diancie Mega", label: "Mega" },
  { speciesId: 691, apiName: "dragalge-mega", displayName: "Dragalge Mega", label: "Mega" },
  { speciesId: 149, apiName: "dragonite-mega", displayName: "Dragonite Mega", label: "Mega" },
  { speciesId: 780, apiName: "drampa-mega", displayName: "Drampa Mega", label: "Mega" },
  { speciesId: 834, apiName: "drednaw-gmax", displayName: "Drednaw G-Max", label: "G-Max" },
  { speciesId: 884, apiName: "duraludon-gmax", displayName: "Duraludon G-Max", label: "G-Max" },
  { speciesId: 604, apiName: "eelektross-mega", displayName: "Eelektross Mega", label: "Mega" },
  { speciesId: 133, apiName: "eevee-gmax", displayName: "Eevee G-Max", label: "G-Max" },
  { speciesId: 500, apiName: "emboar-mega", displayName: "Emboar Mega", label: "Mega" },
  { speciesId: 530, apiName: "excadrill-mega", displayName: "Excadrill Mega", label: "Mega" },
  { speciesId: 870, apiName: "falinks-mega", displayName: "Falinks Mega", label: "Mega" },
  { speciesId: 160, apiName: "feraligatr-mega", displayName: "Feraligatr Mega", label: "Mega" },
  { speciesId: 841, apiName: "flapple-gmax", displayName: "Flapple G-Max", label: "G-Max" },
  { speciesId: 670, apiName: "floette-mega", displayName: "Floette Mega", label: "Mega" },
  { speciesId: 478, apiName: "froslass-mega", displayName: "Froslass Mega", label: "Mega" },
  { speciesId: 475, apiName: "gallade-mega", displayName: "Gallade Mega", label: "Mega" },
  { speciesId: 569, apiName: "garbodor-gmax", displayName: "Garbodor G-Max", label: "G-Max" },
  { speciesId: 445, apiName: "garchomp-mega", displayName: "Garchomp Mega", label: "Mega" },
  { speciesId: 445, apiName: "garchomp-mega-z", displayName: "Garchomp Mega Z", label: "Mega Z" },
  { speciesId: 282, apiName: "gardevoir-mega", displayName: "Gardevoir Mega", label: "Mega" },
  { speciesId: 94, apiName: "gengar-gmax", displayName: "Gengar G-Max", label: "G-Max" },
  { speciesId: 94, apiName: "gengar-mega", displayName: "Gengar Mega", label: "Mega" },
  { speciesId: 362, apiName: "glalie-mega", displayName: "Glalie Mega", label: "Mega" },
  { speciesId: 970, apiName: "glimmora-mega", displayName: "Glimmora Mega", label: "Mega" },
  { speciesId: 768, apiName: "golisopod-mega", displayName: "Golisopod Mega", label: "Mega" },
  { speciesId: 623, apiName: "golurk-mega", displayName: "Golurk Mega", label: "Mega" },
  { speciesId: 658, apiName: "greninja-mega", displayName: "Greninja Mega", label: "Mega" },
  { speciesId: 861, apiName: "grimmsnarl-gmax", displayName: "Grimmsnarl G-Max", label: "G-Max" },
  { speciesId: 383, apiName: "groudon-primal", displayName: "Groudon Primal", label: "Primal" },
  { speciesId: 130, apiName: "gyarados-mega", displayName: "Gyarados Mega", label: "Mega" },
  { speciesId: 858, apiName: "hatterene-gmax", displayName: "Hatterene G-Max", label: "G-Max" },
  { speciesId: 701, apiName: "hawlucha-mega", displayName: "Hawlucha Mega", label: "Mega" },
  { speciesId: 485, apiName: "heatran-mega", displayName: "Heatran Mega", label: "Mega" },
  { speciesId: 214, apiName: "heracross-mega", displayName: "Heracross Mega", label: "Mega" },
  { speciesId: 229, apiName: "houndoom-mega", displayName: "Houndoom Mega", label: "Mega" },
  { speciesId: 818, apiName: "inteleon-gmax", displayName: "Inteleon G-Max", label: "G-Max" },
  { speciesId: 115, apiName: "kangaskhan-mega", displayName: "Kangaskhan Mega", label: "Mega" },
  { speciesId: 99, apiName: "kingler-gmax", displayName: "Kingler G-Max", label: "G-Max" },
  { speciesId: 382, apiName: "kyogre-primal", displayName: "Kyogre Primal", label: "Primal" },
  { speciesId: 131, apiName: "lapras-gmax", displayName: "Lapras G-Max", label: "G-Max" },
  { speciesId: 380, apiName: "latias-mega", displayName: "Latias Mega", label: "Mega" },
  { speciesId: 381, apiName: "latios-mega", displayName: "Latios Mega", label: "Mega" },
  { speciesId: 428, apiName: "lopunny-mega", displayName: "Lopunny Mega", label: "Mega" },
  { speciesId: 448, apiName: "lucario-mega", displayName: "Lucario Mega", label: "Mega" },
  { speciesId: 448, apiName: "lucario-mega-z", displayName: "Lucario Mega Z", label: "Mega Z" },
  { speciesId: 68, apiName: "machamp-gmax", displayName: "Machamp G-Max", label: "G-Max" },
  { speciesId: 801, apiName: "magearna-mega", displayName: "Magearna Mega", label: "Mega" },
  { speciesId: 801, apiName: "magearna-original-mega", displayName: "Magearna Original Mega", label: "Mega" },
  { speciesId: 687, apiName: "malamar-mega", displayName: "Malamar Mega", label: "Mega" },
  { speciesId: 310, apiName: "manectric-mega", displayName: "Manectric Mega", label: "Mega" },
  { speciesId: 303, apiName: "mawile-mega", displayName: "Mawile Mega", label: "Mega" },
  { speciesId: 308, apiName: "medicham-mega", displayName: "Medicham Mega", label: "Mega" },
  { speciesId: 154, apiName: "meganium-mega", displayName: "Meganium Mega", label: "Mega" },
  { speciesId: 809, apiName: "melmetal-gmax", displayName: "Melmetal G-Max", label: "G-Max" },
  { speciesId: 678, apiName: "meowstic-mega", displayName: "Meowstic Mega", label: "Mega" },
  { speciesId: 52, apiName: "meowth-gmax", displayName: "Meowth G-Max", label: "G-Max" },
  { speciesId: 376, apiName: "metagross-mega", displayName: "Metagross Mega", label: "Mega" },
  { speciesId: 150, apiName: "mewtwo-mega-x", displayName: "Mewtwo Mega X", label: "Mega X" },
  { speciesId: 150, apiName: "mewtwo-mega-y", displayName: "Mewtwo Mega Y", label: "Mega Y" },
  { speciesId: 826, apiName: "orbeetle-gmax", displayName: "Orbeetle G-Max", label: "G-Max" },
  { speciesId: 18, apiName: "pidgeot-mega", displayName: "Pidgeot Mega", label: "Mega" },
  { speciesId: 25, apiName: "pikachu-gmax", displayName: "Pikachu G-Max", label: "G-Max" },
  { speciesId: 127, apiName: "pinsir-mega", displayName: "Pinsir Mega", label: "Mega" },
  { speciesId: 668, apiName: "pyroar-mega", displayName: "Pyroar Mega", label: "Mega" },
  { speciesId: 26, apiName: "raichu-mega-x", displayName: "Raichu Mega X", label: "Mega X" },
  { speciesId: 26, apiName: "raichu-mega-y", displayName: "Raichu Mega Y", label: "Mega Y" },
  { speciesId: 384, apiName: "rayquaza-mega", displayName: "Rayquaza Mega", label: "Mega" },
  { speciesId: 812, apiName: "rillaboom-gmax", displayName: "Rillaboom G-Max", label: "G-Max" },
  { speciesId: 302, apiName: "sableye-mega", displayName: "Sableye Mega", label: "Mega" },
  { speciesId: 373, apiName: "salamence-mega", displayName: "Salamence Mega", label: "Mega" },
  { speciesId: 844, apiName: "sandaconda-gmax", displayName: "Sandaconda G-Max", label: "G-Max" },
  { speciesId: 254, apiName: "sceptile-mega", displayName: "Sceptile Mega", label: "Mega" },
  { speciesId: 212, apiName: "scizor-mega", displayName: "Scizor Mega", label: "Mega" },
  { speciesId: 545, apiName: "scolipede-mega", displayName: "Scolipede Mega", label: "Mega" },
  { speciesId: 952, apiName: "scovillain-mega", displayName: "Scovillain Mega", label: "Mega" },
  { speciesId: 560, apiName: "scrafty-mega", displayName: "Scrafty Mega", label: "Mega" },
  { speciesId: 319, apiName: "sharpedo-mega", displayName: "Sharpedo Mega", label: "Mega" },
  { speciesId: 227, apiName: "skarmory-mega", displayName: "Skarmory Mega", label: "Mega" },
  { speciesId: 80, apiName: "slowbro-mega", displayName: "Slowbro Mega", label: "Mega" },
  { speciesId: 143, apiName: "snorlax-gmax", displayName: "Snorlax G-Max", label: "G-Max" },
  { speciesId: 398, apiName: "staraptor-mega", displayName: "Staraptor Mega", label: "Mega" },
  { speciesId: 121, apiName: "starmie-mega", displayName: "Starmie Mega", label: "Mega" },
  { speciesId: 208, apiName: "steelix-mega", displayName: "Steelix Mega", label: "Mega" },
  { speciesId: 260, apiName: "swampert-mega", displayName: "Swampert Mega", label: "Mega" },
  { speciesId: 978, apiName: "tatsugiri-curly-mega", displayName: "Tatsugiri Curly Mega", label: "Mega" },
  { speciesId: 978, apiName: "tatsugiri-droopy-mega", displayName: "Tatsugiri Droopy Mega", label: "Mega" },
  { speciesId: 978, apiName: "tatsugiri-stretchy-mega", displayName: "Tatsugiri Stretchy Mega", label: "Mega" },
  { speciesId: 849, apiName: "toxtricity-amped-gmax", displayName: "Toxtricity Amped G-Max", label: "G-Max" },
  { speciesId: 849, apiName: "toxtricity-low-key-gmax", displayName: "Toxtricity Low Key G-Max", label: "G-Max" },
  { speciesId: 248, apiName: "tyranitar-mega", displayName: "Tyranitar Mega", label: "Mega" },
  { speciesId: 892, apiName: "urshifu-rapid-strike-gmax", displayName: "Urshifu Rapid Strike G-Max", label: "G-Max" },
  { speciesId: 892, apiName: "urshifu-single-strike-gmax", displayName: "Urshifu Single Strike G-Max", label: "G-Max" },
  { speciesId: 3, apiName: "venusaur-gmax", displayName: "Venusaur G-Max", label: "G-Max" },
  { speciesId: 3, apiName: "venusaur-mega", displayName: "Venusaur Mega", label: "Mega" },
  { speciesId: 71, apiName: "victreebel-mega", displayName: "Victreebel Mega", label: "Mega" },
  { speciesId: 807, apiName: "zeraora-mega", displayName: "Zeraora Mega", label: "Mega" },
  { speciesId: 718, apiName: "zygarde-mega", displayName: "Zygarde Mega", label: "Mega" },
];
