export type CosmeticFormConfig = {
  speciesId: number;
  apiName: string; // Stored form_name in living_dex_entries.
  displayName: string;
  label: string;
  dataName?: string; // PokeAPI pokemon or pokemon-form name when different from apiName.
  spriteGender?: "female";
  isRegionalForm?: boolean;
  regionLabel?: string | null;
};

// Generated from Austin Johns Pokemon HOME Organizer LivingForm sheet.
// It includes alternate forms and visible gender differences tracked by Pokemon HOME.
export const COSMETIC_FORMS: CosmeticFormConfig[] = [
  { speciesId: 3, apiName: "venusaur-female", displayName: "Venusaur Female", label: "Female", dataName: "venusaur", spriteGender: "female" },
  { speciesId: 12, apiName: "butterfree-female", displayName: "Butterfree Female", label: "Female", dataName: "butterfree", spriteGender: "female" },
  { speciesId: 19, apiName: "rattata-female", displayName: "Rattata Female", label: "Female", dataName: "rattata", spriteGender: "female" },
  { speciesId: 19, apiName: "rattata-alola", displayName: "Rattata Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 20, apiName: "raticate-female", displayName: "Raticate Female", label: "Female", dataName: "raticate", spriteGender: "female" },
  { speciesId: 20, apiName: "raticate-alola", displayName: "Raticate Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 25, apiName: "pikachu-female", displayName: "Pikachu Female", label: "Female", dataName: "pikachu", spriteGender: "female" },
  { speciesId: 25, apiName: "pikachu-original-cap", displayName: "Pikachu Original Cap", label: "Original Cap" },
  { speciesId: 25, apiName: "pikachu-hoenn-cap", displayName: "Pikachu Hoenn Cap", label: "Hoenn Cap" },
  { speciesId: 25, apiName: "pikachu-sinnoh-cap", displayName: "Pikachu Sinnoh Cap", label: "Sinnoh Cap" },
  { speciesId: 25, apiName: "pikachu-unova-cap", displayName: "Pikachu Unova Cap", label: "Unova Cap" },
  { speciesId: 25, apiName: "pikachu-kalos-cap", displayName: "Pikachu Kalos Cap", label: "Kalos Cap" },
  { speciesId: 25, apiName: "pikachu-alola-cap", displayName: "Pikachu Alola Cap", label: "Alola Cap" },
  { speciesId: 25, apiName: "pikachu-partner-cap", displayName: "Pikachu Partner Cap", label: "Partner Cap" },
  { speciesId: 25, apiName: "pikachu-world-cap", displayName: "Pikachu World Cap", label: "World Cap" },
  { speciesId: 26, apiName: "raichu-female", displayName: "Raichu Female", label: "Female", dataName: "raichu", spriteGender: "female" },
  { speciesId: 26, apiName: "raichu-alola", displayName: "Raichu Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 27, apiName: "sandshrew-alola", displayName: "Sandshrew Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 28, apiName: "sandslash-alola", displayName: "Sandslash Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 37, apiName: "vulpix-alola", displayName: "Vulpix Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 38, apiName: "ninetales-alola", displayName: "Ninetales Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 41, apiName: "zubat-female", displayName: "Zubat Female", label: "Female", dataName: "zubat", spriteGender: "female" },
  { speciesId: 42, apiName: "golbat-female", displayName: "Golbat Female", label: "Female", dataName: "golbat", spriteGender: "female" },
  { speciesId: 44, apiName: "gloom-female", displayName: "Gloom Female", label: "Female", dataName: "gloom", spriteGender: "female" },
  { speciesId: 45, apiName: "vileplume-female", displayName: "Vileplume Female", label: "Female", dataName: "vileplume", spriteGender: "female" },
  { speciesId: 50, apiName: "diglett-alola", displayName: "Diglett Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 51, apiName: "dugtrio-alola", displayName: "Dugtrio Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 52, apiName: "meowth-alola", displayName: "Meowth Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 52, apiName: "meowth-galar", displayName: "Meowth Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 53, apiName: "persian-alola", displayName: "Persian Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 58, apiName: "growlithe-hisui", displayName: "Growlithe Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 59, apiName: "arcanine-hisui", displayName: "Arcanine Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 64, apiName: "kadabra-female", displayName: "Kadabra Female", label: "Female", dataName: "kadabra", spriteGender: "female" },
  { speciesId: 65, apiName: "alakazam-female", displayName: "Alakazam Female", label: "Female", dataName: "alakazam", spriteGender: "female" },
  { speciesId: 74, apiName: "geodude-alola", displayName: "Geodude Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 75, apiName: "graveler-alola", displayName: "Graveler Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 76, apiName: "golem-alola", displayName: "Golem Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 77, apiName: "ponyta-galar", displayName: "Ponyta Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 78, apiName: "rapidash-galar", displayName: "Rapidash Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 79, apiName: "slowpoke-galar", displayName: "Slowpoke Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 80, apiName: "slowbro-galar", displayName: "Slowbro Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 83, apiName: "farfetchd-galar", displayName: "Farfetch'd Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 84, apiName: "doduo-female", displayName: "Doduo Female", label: "Female", dataName: "doduo", spriteGender: "female" },
  { speciesId: 85, apiName: "dodrio-female", displayName: "Dodrio Female", label: "Female", dataName: "dodrio", spriteGender: "female" },
  { speciesId: 88, apiName: "grimer-alola", displayName: "Grimer Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 89, apiName: "muk-alola", displayName: "Muk Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 97, apiName: "hypno-female", displayName: "Hypno Female", label: "Female", dataName: "hypno", spriteGender: "female" },
  { speciesId: 100, apiName: "voltorb-hisui", displayName: "Voltorb Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 101, apiName: "electrode-hisui", displayName: "Electrode Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 103, apiName: "exeggutor-alola", displayName: "Exeggutor Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 105, apiName: "marowak-alola", displayName: "Marowak Alolan", label: "Alolan", isRegionalForm: true, regionLabel: "Alolan" },
  { speciesId: 110, apiName: "weezing-galar", displayName: "Weezing Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 111, apiName: "rhyhorn-female", displayName: "Rhyhorn Female", label: "Female", dataName: "rhyhorn", spriteGender: "female" },
  { speciesId: 112, apiName: "rhydon-female", displayName: "Rhydon Female", label: "Female", dataName: "rhydon", spriteGender: "female" },
  { speciesId: 118, apiName: "goldeen-female", displayName: "Goldeen Female", label: "Female", dataName: "goldeen", spriteGender: "female" },
  { speciesId: 119, apiName: "seaking-female", displayName: "Seaking Female", label: "Female", dataName: "seaking", spriteGender: "female" },
  { speciesId: 122, apiName: "mr-mime-galar", displayName: "Mr. Mime Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 123, apiName: "scyther-female", displayName: "Scyther Female", label: "Female", dataName: "scyther", spriteGender: "female" },
  { speciesId: 128, apiName: "tauros-paldea-combat-breed", displayName: "Tauros Paldean Combat Breed", label: "Paldean", isRegionalForm: true, regionLabel: "Paldean" },
  { speciesId: 128, apiName: "tauros-paldea-blaze-breed", displayName: "Tauros Paldean Blaze Breed", label: "Paldean", isRegionalForm: true, regionLabel: "Paldean" },
  { speciesId: 128, apiName: "tauros-paldea-aqua-breed", displayName: "Tauros Paldean Aqua Breed", label: "Paldean", isRegionalForm: true, regionLabel: "Paldean" },
  { speciesId: 129, apiName: "magikarp-female", displayName: "Magikarp Female", label: "Female", dataName: "magikarp", spriteGender: "female" },
  { speciesId: 130, apiName: "gyarados-female", displayName: "Gyarados Female", label: "Female", dataName: "gyarados", spriteGender: "female" },
  { speciesId: 133, apiName: "eevee-female", displayName: "Eevee Female", label: "Female", dataName: "eevee", spriteGender: "female" },
  { speciesId: 144, apiName: "articuno-galar", displayName: "Articuno Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 145, apiName: "zapdos-galar", displayName: "Zapdos Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 146, apiName: "moltres-galar", displayName: "Moltres Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 154, apiName: "meganium-female", displayName: "Meganium Female", label: "Female", dataName: "meganium", spriteGender: "female" },
  { speciesId: 157, apiName: "typhlosion-hisui", displayName: "Typhlosion Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 165, apiName: "ledyba-female", displayName: "Ledyba Female", label: "Female", dataName: "ledyba", spriteGender: "female" },
  { speciesId: 166, apiName: "ledian-female", displayName: "Ledian Female", label: "Female", dataName: "ledian", spriteGender: "female" },
  { speciesId: 178, apiName: "xatu-female", displayName: "Xatu Female", label: "Female", dataName: "xatu", spriteGender: "female" },
  { speciesId: 185, apiName: "sudowoodo-female", displayName: "Sudowoodo Female", label: "Female", dataName: "sudowoodo", spriteGender: "female" },
  { speciesId: 186, apiName: "politoed-female", displayName: "Politoed Female", label: "Female", dataName: "politoed", spriteGender: "female" },
  { speciesId: 190, apiName: "aipom-female", displayName: "Aipom Female", label: "Female", dataName: "aipom", spriteGender: "female" },
  { speciesId: 194, apiName: "wooper-female", displayName: "Wooper Female", label: "Female", dataName: "wooper", spriteGender: "female" },
  { speciesId: 194, apiName: "wooper-paldea", displayName: "Wooper Paldean", label: "Paldean", isRegionalForm: true, regionLabel: "Paldean" },
  { speciesId: 195, apiName: "quagsire-female", displayName: "Quagsire Female", label: "Female", dataName: "quagsire", spriteGender: "female" },
  { speciesId: 198, apiName: "murkrow-female", displayName: "Murkrow Female", label: "Female", dataName: "murkrow", spriteGender: "female" },
  { speciesId: 199, apiName: "slowking-galar", displayName: "Slowking Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 201, apiName: "unown-b", displayName: "Unown b", label: "b" },
  { speciesId: 201, apiName: "unown-c", displayName: "Unown c", label: "c" },
  { speciesId: 201, apiName: "unown-d", displayName: "Unown d", label: "d" },
  { speciesId: 201, apiName: "unown-e", displayName: "Unown e", label: "e" },
  { speciesId: 201, apiName: "unown-f", displayName: "Unown f", label: "f" },
  { speciesId: 201, apiName: "unown-g", displayName: "Unown g", label: "g" },
  { speciesId: 201, apiName: "unown-h", displayName: "Unown h", label: "h" },
  { speciesId: 201, apiName: "unown-i", displayName: "Unown i", label: "i" },
  { speciesId: 201, apiName: "unown-j", displayName: "Unown j", label: "j" },
  { speciesId: 201, apiName: "unown-k", displayName: "Unown k", label: "k" },
  { speciesId: 201, apiName: "unown-l", displayName: "Unown l", label: "l" },
  { speciesId: 201, apiName: "unown-m", displayName: "Unown m", label: "m" },
  { speciesId: 201, apiName: "unown-n", displayName: "Unown n", label: "n" },
  { speciesId: 201, apiName: "unown-o", displayName: "Unown o", label: "o" },
  { speciesId: 201, apiName: "unown-p", displayName: "Unown p", label: "p" },
  { speciesId: 201, apiName: "unown-q", displayName: "Unown q", label: "q" },
  { speciesId: 201, apiName: "unown-r", displayName: "Unown r", label: "r" },
  { speciesId: 201, apiName: "unown-s", displayName: "Unown s", label: "s" },
  { speciesId: 201, apiName: "unown-t", displayName: "Unown t", label: "t" },
  { speciesId: 201, apiName: "unown-u", displayName: "Unown u", label: "u" },
  { speciesId: 201, apiName: "unown-v", displayName: "Unown v", label: "v" },
  { speciesId: 201, apiName: "unown-w", displayName: "Unown w", label: "w" },
  { speciesId: 201, apiName: "unown-x", displayName: "Unown x", label: "x" },
  { speciesId: 201, apiName: "unown-y", displayName: "Unown y", label: "y" },
  { speciesId: 201, apiName: "unown-z", displayName: "Unown z", label: "z" },
  { speciesId: 201, apiName: "unown-exclamation", displayName: "Unown !", label: "!" },
  { speciesId: 201, apiName: "unown-question", displayName: "Unown ?", label: "?" },
  { speciesId: 202, apiName: "wobbuffet-female", displayName: "Wobbuffet Female", label: "Female", dataName: "wobbuffet", spriteGender: "female" },
  { speciesId: 203, apiName: "girafarig-female", displayName: "Girafarig Female", label: "Female", dataName: "girafarig", spriteGender: "female" },
  { speciesId: 207, apiName: "gligar-female", displayName: "Gligar Female", label: "Female", dataName: "gligar", spriteGender: "female" },
  { speciesId: 208, apiName: "steelix-female", displayName: "Steelix Female", label: "Female", dataName: "steelix", spriteGender: "female" },
  { speciesId: 211, apiName: "qwilfish-hisui", displayName: "Qwilfish Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 212, apiName: "scizor-female", displayName: "Scizor Female", label: "Female", dataName: "scizor", spriteGender: "female" },
  { speciesId: 214, apiName: "heracross-female", displayName: "Heracross Female", label: "Female", dataName: "heracross", spriteGender: "female" },
  { speciesId: 215, apiName: "sneasel-female", displayName: "Sneasel Female", label: "Female", dataName: "sneasel", spriteGender: "female" },
  { speciesId: 215, apiName: "sneasel-hisui", displayName: "Sneasel Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 215, apiName: "sneasel-hisui-female", displayName: "Sneasel Hisuian Female", label: "Female", dataName: "sneasel-hisui", spriteGender: "female", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 217, apiName: "ursaring-female", displayName: "Ursaring Female", label: "Female", dataName: "ursaring", spriteGender: "female" },
  { speciesId: 221, apiName: "piloswine-female", displayName: "Piloswine Female", label: "Female", dataName: "piloswine", spriteGender: "female" },
  { speciesId: 222, apiName: "corsola-galar", displayName: "Corsola Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 224, apiName: "octillery-female", displayName: "Octillery Female", label: "Female", dataName: "octillery", spriteGender: "female" },
  { speciesId: 229, apiName: "houndoom-female", displayName: "Houndoom Female", label: "Female", dataName: "houndoom", spriteGender: "female" },
  { speciesId: 232, apiName: "donphan-female", displayName: "Donphan Female", label: "Female", dataName: "donphan", spriteGender: "female" },
  { speciesId: 255, apiName: "torchic-female", displayName: "Torchic Female", label: "Female", dataName: "torchic", spriteGender: "female" },
  { speciesId: 256, apiName: "combusken-female", displayName: "Combusken Female", label: "Female", dataName: "combusken", spriteGender: "female" },
  { speciesId: 257, apiName: "blaziken-female", displayName: "Blaziken Female", label: "Female", dataName: "blaziken", spriteGender: "female" },
  { speciesId: 263, apiName: "zigzagoon-galar", displayName: "Zigzagoon Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 264, apiName: "linoone-galar", displayName: "Linoone Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 267, apiName: "beautifly-female", displayName: "Beautifly Female", label: "Female", dataName: "beautifly", spriteGender: "female" },
  { speciesId: 269, apiName: "dustox-female", displayName: "Dustox Female", label: "Female", dataName: "dustox", spriteGender: "female" },
  { speciesId: 272, apiName: "ludicolo-female", displayName: "Ludicolo Female", label: "Female", dataName: "ludicolo", spriteGender: "female" },
  { speciesId: 274, apiName: "nuzleaf-female", displayName: "Nuzleaf Female", label: "Female", dataName: "nuzleaf", spriteGender: "female" },
  { speciesId: 275, apiName: "shiftry-female", displayName: "Shiftry Female", label: "Female", dataName: "shiftry", spriteGender: "female" },
  { speciesId: 307, apiName: "meditite-female", displayName: "Meditite Female", label: "Female", dataName: "meditite", spriteGender: "female" },
  { speciesId: 308, apiName: "medicham-female", displayName: "Medicham Female", label: "Female", dataName: "medicham", spriteGender: "female" },
  { speciesId: 315, apiName: "roselia-female", displayName: "Roselia Female", label: "Female", dataName: "roselia", spriteGender: "female" },
  { speciesId: 316, apiName: "gulpin-female", displayName: "Gulpin Female", label: "Female", dataName: "gulpin", spriteGender: "female" },
  { speciesId: 317, apiName: "swalot-female", displayName: "Swalot Female", label: "Female", dataName: "swalot", spriteGender: "female" },
  { speciesId: 322, apiName: "numel-female", displayName: "Numel Female", label: "Female", dataName: "numel", spriteGender: "female" },
  { speciesId: 323, apiName: "camerupt-female", displayName: "Camerupt Female", label: "Female", dataName: "camerupt", spriteGender: "female" },
  { speciesId: 332, apiName: "cacturne-female", displayName: "Cacturne Female", label: "Female", dataName: "cacturne", spriteGender: "female" },
  { speciesId: 350, apiName: "milotic-female", displayName: "Milotic Female", label: "Female", dataName: "milotic", spriteGender: "female" },
  { speciesId: 369, apiName: "relicanth-female", displayName: "Relicanth Female", label: "Female", dataName: "relicanth", spriteGender: "female" },
  { speciesId: 386, apiName: "deoxys-attack", displayName: "Deoxys Attack", label: "Attack" },
  { speciesId: 386, apiName: "deoxys-defense", displayName: "Deoxys Defense", label: "Defense" },
  { speciesId: 386, apiName: "deoxys-speed", displayName: "Deoxys Speed", label: "Speed" },
  { speciesId: 396, apiName: "starly-female", displayName: "Starly Female", label: "Female", dataName: "starly", spriteGender: "female" },
  { speciesId: 397, apiName: "staravia-female", displayName: "Staravia Female", label: "Female", dataName: "staravia", spriteGender: "female" },
  { speciesId: 398, apiName: "staraptor-female", displayName: "Staraptor Female", label: "Female", dataName: "staraptor", spriteGender: "female" },
  { speciesId: 399, apiName: "bidoof-female", displayName: "Bidoof Female", label: "Female", dataName: "bidoof", spriteGender: "female" },
  { speciesId: 400, apiName: "bibarel-female", displayName: "Bibarel Female", label: "Female", dataName: "bibarel", spriteGender: "female" },
  { speciesId: 401, apiName: "kricketot-female", displayName: "Kricketot Female", label: "Female", dataName: "kricketot", spriteGender: "female" },
  { speciesId: 402, apiName: "kricketune-female", displayName: "Kricketune Female", label: "Female", dataName: "kricketune", spriteGender: "female" },
  { speciesId: 403, apiName: "shinx-female", displayName: "Shinx Female", label: "Female", dataName: "shinx", spriteGender: "female" },
  { speciesId: 404, apiName: "luxio-female", displayName: "Luxio Female", label: "Female", dataName: "luxio", spriteGender: "female" },
  { speciesId: 405, apiName: "luxray-female", displayName: "Luxray Female", label: "Female", dataName: "luxray", spriteGender: "female" },
  { speciesId: 407, apiName: "roserade-female", displayName: "Roserade Female", label: "Female", dataName: "roserade", spriteGender: "female" },
  { speciesId: 412, apiName: "burmy-sandy", displayName: "Burmy Sandy", label: "Sandy" },
  { speciesId: 412, apiName: "burmy-trash", displayName: "Burmy Trash", label: "Trash" },
  { speciesId: 413, apiName: "wormadam-sandy", displayName: "Wormadam Sandy", label: "Sandy" },
  { speciesId: 413, apiName: "wormadam-trash", displayName: "Wormadam Trash", label: "Trash" },
  { speciesId: 415, apiName: "combee-female", displayName: "Combee Female", label: "Female", dataName: "combee", spriteGender: "female" },
  { speciesId: 417, apiName: "pachirisu-female", displayName: "Pachirisu Female", label: "Female", dataName: "pachirisu", spriteGender: "female" },
  { speciesId: 418, apiName: "buizel-female", displayName: "Buizel Female", label: "Female", dataName: "buizel", spriteGender: "female" },
  { speciesId: 419, apiName: "floatzel-female", displayName: "Floatzel Female", label: "Female", dataName: "floatzel", spriteGender: "female" },
  { speciesId: 422, apiName: "shellos-east", displayName: "Shellos East Sea", label: "East Sea" },
  { speciesId: 423, apiName: "gastrodon-east", displayName: "Gastrodon East Sea", label: "East Sea" },
  { speciesId: 424, apiName: "ambipom-female", displayName: "Ambipom Female", label: "Female", dataName: "ambipom", spriteGender: "female" },
  { speciesId: 443, apiName: "gible-female", displayName: "Gible Female", label: "Female", dataName: "gible", spriteGender: "female" },
  { speciesId: 444, apiName: "gabite-female", displayName: "Gabite Female", label: "Female", dataName: "gabite", spriteGender: "female" },
  { speciesId: 445, apiName: "garchomp-female", displayName: "Garchomp Female", label: "Female", dataName: "garchomp", spriteGender: "female" },
  { speciesId: 449, apiName: "hippopotas-female", displayName: "Hippopotas Female", label: "Female", dataName: "hippopotas", spriteGender: "female" },
  { speciesId: 450, apiName: "hippowdon-female", displayName: "Hippowdon Female", label: "Female", dataName: "hippowdon", spriteGender: "female" },
  { speciesId: 453, apiName: "croagunk-female", displayName: "Croagunk Female", label: "Female", dataName: "croagunk", spriteGender: "female" },
  { speciesId: 454, apiName: "toxicroak-female", displayName: "Toxicroak Female", label: "Female", dataName: "toxicroak", spriteGender: "female" },
  { speciesId: 456, apiName: "finneon-female", displayName: "Finneon Female", label: "Female", dataName: "finneon", spriteGender: "female" },
  { speciesId: 457, apiName: "lumineon-female", displayName: "Lumineon Female", label: "Female", dataName: "lumineon", spriteGender: "female" },
  { speciesId: 459, apiName: "snover-female", displayName: "Snover Female", label: "Female", dataName: "snover", spriteGender: "female" },
  { speciesId: 460, apiName: "abomasnow-female", displayName: "Abomasnow Female", label: "Female", dataName: "abomasnow", spriteGender: "female" },
  { speciesId: 461, apiName: "weavile-female", displayName: "Weavile Female", label: "Female", dataName: "weavile", spriteGender: "female" },
  { speciesId: 464, apiName: "rhyperior-female", displayName: "Rhyperior Female", label: "Female", dataName: "rhyperior", spriteGender: "female" },
  { speciesId: 465, apiName: "tangrowth-female", displayName: "Tangrowth Female", label: "Female", dataName: "tangrowth", spriteGender: "female" },
  { speciesId: 473, apiName: "mamoswine-female", displayName: "Mamoswine Female", label: "Female", dataName: "mamoswine", spriteGender: "female" },
  { speciesId: 479, apiName: "rotom-heat", displayName: "Rotom Heat", label: "Heat" },
  { speciesId: 479, apiName: "rotom-wash", displayName: "Rotom Wash", label: "Wash" },
  { speciesId: 479, apiName: "rotom-frost", displayName: "Rotom Frost", label: "Frost" },
  { speciesId: 479, apiName: "rotom-fan", displayName: "Rotom Fan", label: "Fan" },
  { speciesId: 479, apiName: "rotom-mow", displayName: "Rotom Mow", label: "Mow" },
  { speciesId: 492, apiName: "shaymin-sky", displayName: "Shaymin Sky", label: "Sky" },
  { speciesId: 503, apiName: "samurott-hisui", displayName: "Samurott Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 521, apiName: "unfezant-female", displayName: "Unfezant Female", label: "Female", dataName: "unfezant", spriteGender: "female" },
  { speciesId: 549, apiName: "lilligant-hisui", displayName: "Lilligant Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 550, apiName: "basculin-blue-striped", displayName: "Basculin Blue Stripe", label: "Blue Stripe" },
  { speciesId: 550, apiName: "basculin-white-striped", displayName: "Basculin White Stripe", label: "White Stripe" },
  { speciesId: 554, apiName: "darumaka-galar", displayName: "Darumaka Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 555, apiName: "darmanitan-galar-standard", displayName: "Darmanitan Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 562, apiName: "yamask-galar", displayName: "Yamask Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 570, apiName: "zorua-hisui", displayName: "Zorua Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 571, apiName: "zoroark-hisui", displayName: "Zoroark Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 585, apiName: "deerling-summer", displayName: "Deerling Summer", label: "Summer" },
  { speciesId: 585, apiName: "deerling-autumn", displayName: "Deerling Fall", label: "Fall" },
  { speciesId: 585, apiName: "deerling-winter", displayName: "Deerling Winter", label: "Winter" },
  { speciesId: 586, apiName: "sawsbuck-summer", displayName: "Sawsbuck Summer", label: "Summer" },
  { speciesId: 586, apiName: "sawsbuck-autumn", displayName: "Sawsbuck Fall", label: "Fall" },
  { speciesId: 586, apiName: "sawsbuck-winter", displayName: "Sawsbuck Winter", label: "Winter" },
  { speciesId: 592, apiName: "frillish-female", displayName: "Frillish Female", label: "Female" },
  { speciesId: 593, apiName: "jellicent-female", displayName: "Jellicent Female", label: "Female" },
  { speciesId: 618, apiName: "stunfisk-galar", displayName: "Stunfisk Galarian", label: "Galarian", isRegionalForm: true, regionLabel: "Galarian" },
  { speciesId: 628, apiName: "braviary-hisui", displayName: "Braviary Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 641, apiName: "tornadus-therian", displayName: "Tornadus Therian", label: "Therian" },
  { speciesId: 642, apiName: "thundurus-therian", displayName: "Thundurus Therian", label: "Therian" },
  { speciesId: 645, apiName: "landorus-therian", displayName: "Landorus Therian", label: "Therian" },
  { speciesId: 647, apiName: "keldeo-resolute", displayName: "Keldeo Resolute", label: "Resolute" },
  { speciesId: 666, apiName: "vivillon-polar", displayName: "Vivillon Polar", label: "Polar" },
  { speciesId: 666, apiName: "vivillon-tundra", displayName: "Vivillon Tundra", label: "Tundra" },
  { speciesId: 666, apiName: "vivillon-continental", displayName: "Vivillon Continental", label: "Continental" },
  { speciesId: 666, apiName: "vivillon-garden", displayName: "Vivillon Garden", label: "Garden" },
  { speciesId: 666, apiName: "vivillon-elegant", displayName: "Vivillon Elegant", label: "Elegant" },
  { speciesId: 666, apiName: "vivillon-meadow", displayName: "Vivillon Meadow", label: "Meadow" },
  { speciesId: 666, apiName: "vivillon-modern", displayName: "Vivillon Modern", label: "Modern" },
  { speciesId: 666, apiName: "vivillon-marine", displayName: "Vivillon Marine", label: "Marine" },
  { speciesId: 666, apiName: "vivillon-archipelago", displayName: "Vivillon Archipelago", label: "Archipelago" },
  { speciesId: 666, apiName: "vivillon-high-plains", displayName: "Vivillon High Plains", label: "High Plains" },
  { speciesId: 666, apiName: "vivillon-sandstorm", displayName: "Vivillon Sandstorm", label: "Sandstorm" },
  { speciesId: 666, apiName: "vivillon-river", displayName: "Vivillon River", label: "River" },
  { speciesId: 666, apiName: "vivillon-monsoon", displayName: "Vivillon Monsoon", label: "Monsoon" },
  { speciesId: 666, apiName: "vivillon-savanna", displayName: "Vivillon Savanna", label: "Savanna" },
  { speciesId: 666, apiName: "vivillon-sun", displayName: "Vivillon Sun", label: "Sun" },
  { speciesId: 666, apiName: "vivillon-ocean", displayName: "Vivillon Ocean", label: "Ocean" },
  { speciesId: 666, apiName: "vivillon-jungle", displayName: "Vivillon Jungle", label: "Jungle" },
  { speciesId: 666, apiName: "vivillon-fancy", displayName: "Vivillon Fancy", label: "Fancy" },
  { speciesId: 666, apiName: "vivillon-poke-ball", displayName: "Vivillon Poké Ball", label: "Poké Ball" },
  { speciesId: 668, apiName: "pyroar-female", displayName: "Pyroar Female", label: "Female" },
  { speciesId: 669, apiName: "flabebe-yellow", displayName: "Flabébé Yellow Flower", label: "Yellow Flower" },
  { speciesId: 669, apiName: "flabebe-orange", displayName: "Flabébé Orange Flower", label: "Orange Flower" },
  { speciesId: 669, apiName: "flabebe-blue", displayName: "Flabébé Blue Flower", label: "Blue Flower" },
  { speciesId: 669, apiName: "flabebe-white", displayName: "Flabébé White Flower", label: "White Flower" },
  { speciesId: 670, apiName: "floette-yellow", displayName: "Floette Yellow Flower", label: "Yellow Flower" },
  { speciesId: 670, apiName: "floette-orange", displayName: "Floette Orange Flower", label: "Orange Flower" },
  { speciesId: 670, apiName: "floette-blue", displayName: "Floette Blue Flower", label: "Blue Flower" },
  { speciesId: 670, apiName: "floette-white", displayName: "Floette White Flower", label: "White Flower" },
  { speciesId: 670, apiName: "floette-eternal", displayName: "Floette Eternal Flower", label: "Eternal Flower" },
  { speciesId: 671, apiName: "florges-yellow", displayName: "Florges Yellow Flower", label: "Yellow Flower" },
  { speciesId: 671, apiName: "florges-orange", displayName: "Florges Orange Flower", label: "Orange Flower" },
  { speciesId: 671, apiName: "florges-blue", displayName: "Florges Blue Flower", label: "Blue Flower" },
  { speciesId: 671, apiName: "florges-white", displayName: "Florges White Flower", label: "White Flower" },
  { speciesId: 676, apiName: "furfrou-heart", displayName: "Furfrou Heart", label: "Heart" },
  { speciesId: 676, apiName: "furfrou-star", displayName: "Furfrou Star", label: "Star" },
  { speciesId: 676, apiName: "furfrou-diamond", displayName: "Furfrou Diamond", label: "Diamond" },
  { speciesId: 676, apiName: "furfrou-debutante", displayName: "Furfrou Debutante", label: "Debutante" },
  { speciesId: 676, apiName: "furfrou-matron", displayName: "Furfrou Matron", label: "Matron" },
  { speciesId: 676, apiName: "furfrou-dandy", displayName: "Furfrou Dandy", label: "Dandy" },
  { speciesId: 676, apiName: "furfrou-la-reine", displayName: "Furfrou La Reine", label: "La Reine" },
  { speciesId: 676, apiName: "furfrou-kabuki", displayName: "Furfrou Kabuki", label: "Kabuki" },
  { speciesId: 676, apiName: "furfrou-pharaoh", displayName: "Furfrou Pharaoh", label: "Pharaoh" },
  { speciesId: 678, apiName: "meowstic-female", displayName: "Meowstic Female", label: "Female" },
  { speciesId: 705, apiName: "sliggoo-hisui", displayName: "Sliggoo Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 706, apiName: "goodra-hisui", displayName: "Goodra Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 710, apiName: "pumpkaboo-small", displayName: "Pumpkaboo Small", label: "Small" },
  { speciesId: 710, apiName: "pumpkaboo-large", displayName: "Pumpkaboo Large", label: "Large" },
  { speciesId: 710, apiName: "pumpkaboo-super", displayName: "Pumpkaboo Super", label: "Super" },
  { speciesId: 711, apiName: "gourgeist-small", displayName: "Gourgeist Small", label: "Small" },
  { speciesId: 711, apiName: "gourgeist-large", displayName: "Gourgeist Large", label: "Large" },
  { speciesId: 711, apiName: "gourgeist-super", displayName: "Gourgeist Super", label: "Super" },
  { speciesId: 713, apiName: "avalugg-hisui", displayName: "Avalugg Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 718, apiName: "zygarde-10", displayName: "Zygarde 10%", label: "10%" },
  { speciesId: 720, apiName: "hoopa-unbound", displayName: "Hoopa Unbound", label: "Unbound" },
  { speciesId: 724, apiName: "decidueye-hisui", displayName: "Decidueye Hisuian", label: "Hisuian", isRegionalForm: true, regionLabel: "Hisuian" },
  { speciesId: 741, apiName: "oricorio-pom-pom", displayName: "Oricorio Pom-Pom Style", label: "Pom-Pom Style" },
  { speciesId: 741, apiName: "oricorio-pau", displayName: "Oricorio Pa'u Style", label: "Pa'u Style" },
  { speciesId: 741, apiName: "oricorio-sensu", displayName: "Oricorio Sensu Style", label: "Sensu Style" },
  { speciesId: 745, apiName: "lycanroc-midnight", displayName: "Lycanroc Midnight", label: "Midnight" },
  { speciesId: 745, apiName: "lycanroc-dusk", displayName: "Lycanroc Dusk", label: "Dusk" },
  { speciesId: 774, apiName: "minior-orange", displayName: "Minior Orange Core", label: "Orange Core" },
  { speciesId: 774, apiName: "minior-yellow", displayName: "Minior Yellow Core", label: "Yellow Core" },
  { speciesId: 774, apiName: "minior-green", displayName: "Minior Green Core", label: "Green Core" },
  { speciesId: 774, apiName: "minior-blue", displayName: "Minior Blue Core", label: "Blue Core" },
  { speciesId: 774, apiName: "minior-indigo", displayName: "Minior Indigo Core", label: "Indigo Core" },
  { speciesId: 774, apiName: "minior-violet", displayName: "Minior Violet Core", label: "Violet Core" },
  { speciesId: 801, apiName: "magearna-original", displayName: "Magearna Original Pokeball", label: "Original Pokeball" },
  { speciesId: 849, apiName: "toxtricity-low-key", displayName: "Toxtricity Low Key", label: "Low Key" },
  { speciesId: 854, apiName: "sinistea-antique", displayName: "Sinistea Antique Form", label: "Antique Form" },
  { speciesId: 855, apiName: "polteageist-antique", displayName: "Polteageist Antique Form", label: "Antique Form" },
  { speciesId: 869, apiName: "alcremie-vanilla-cream-berry-sweet", displayName: "Alcremie Vanilla Cream, Berry", label: "Vanilla Cream, Berry" },
  { speciesId: 869, apiName: "alcremie-vanilla-cream-love-sweet", displayName: "Alcremie Vanilla Cream, Love", label: "Vanilla Cream, Love" },
  { speciesId: 869, apiName: "alcremie-vanilla-cream-star-sweet", displayName: "Alcremie Vanilla Cream, Star", label: "Vanilla Cream, Star" },
  { speciesId: 869, apiName: "alcremie-vanilla-cream-clover-sweet", displayName: "Alcremie Vanilla Cream, Clover", label: "Vanilla Cream, Clover" },
  { speciesId: 869, apiName: "alcremie-vanilla-cream-flower-sweet", displayName: "Alcremie Vanilla Cream, Flower", label: "Vanilla Cream, Flower" },
  { speciesId: 869, apiName: "alcremie-vanilla-cream-ribbon-sweet", displayName: "Alcremie Vanilla Cream, Ribbon", label: "Vanilla Cream, Ribbon" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-strawberry-sweet", displayName: "Alcremie Ruby Cream, Strawberry", label: "Ruby Cream, Strawberry" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-berry-sweet", displayName: "Alcremie Ruby Cream, Berry", label: "Ruby Cream, Berry" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-love-sweet", displayName: "Alcremie Ruby Cream, Love", label: "Ruby Cream, Love" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-star-sweet", displayName: "Alcremie Ruby Cream, Star", label: "Ruby Cream, Star" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-clover-sweet", displayName: "Alcremie Ruby Cream, Clover", label: "Ruby Cream, Clover" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-flower-sweet", displayName: "Alcremie Ruby Cream, Flower", label: "Ruby Cream, Flower" },
  { speciesId: 869, apiName: "alcremie-ruby-cream-ribbon-sweet", displayName: "Alcremie Ruby Cream, Ribbon", label: "Ruby Cream, Ribbon" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-strawberry-sweet", displayName: "Alcremie Matcha Cream, Strawberry", label: "Matcha Cream, Strawberry" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-berry-sweet", displayName: "Alcremie Matcha Cream, Berry", label: "Matcha Cream, Berry" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-love-sweet", displayName: "Alcremie Matcha Cream, Love", label: "Matcha Cream, Love" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-star-sweet", displayName: "Alcremie Matcha Cream, Star", label: "Matcha Cream, Star" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-clover-sweet", displayName: "Alcremie Matcha Cream, Clover", label: "Matcha Cream, Clover" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-flower-sweet", displayName: "Alcremie Matcha Cream, Flower", label: "Matcha Cream, Flower" },
  { speciesId: 869, apiName: "alcremie-matcha-cream-ribbon-sweet", displayName: "Alcremie Matcha Cream, Ribbon", label: "Matcha Cream, Ribbon" },
  { speciesId: 869, apiName: "alcremie-mint-cream-strawberry-sweet", displayName: "Alcremie Mint Cream, Strawberry", label: "Mint Cream, Strawberry" },
  { speciesId: 869, apiName: "alcremie-mint-cream-berry-sweet", displayName: "Alcremie Mint Cream, Berry", label: "Mint Cream, Berry" },
  { speciesId: 869, apiName: "alcremie-mint-cream-love-sweet", displayName: "Alcremie Mint Cream, Love", label: "Mint Cream, Love" },
  { speciesId: 869, apiName: "alcremie-mint-cream-star-sweet", displayName: "Alcremie Mint Cream, Star", label: "Mint Cream, Star" },
  { speciesId: 869, apiName: "alcremie-mint-cream-clover-sweet", displayName: "Alcremie Mint Cream, Clover", label: "Mint Cream, Clover" },
  { speciesId: 869, apiName: "alcremie-mint-cream-flower-sweet", displayName: "Alcremie Mint Cream, Flower", label: "Mint Cream, Flower" },
  { speciesId: 869, apiName: "alcremie-mint-cream-ribbon-sweet", displayName: "Alcremie Mint Cream, Ribbon", label: "Mint Cream, Ribbon" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-strawberry-sweet", displayName: "Alcremie Lemon Cream, Strawberry", label: "Lemon Cream, Strawberry" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-berry-sweet", displayName: "Alcremie Lemon Cream, Berry", label: "Lemon Cream, Berry" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-love-sweet", displayName: "Alcremie Lemon Cream, Love", label: "Lemon Cream, Love" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-star-sweet", displayName: "Alcremie Lemon Cream, Star", label: "Lemon Cream, Star" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-clover-sweet", displayName: "Alcremie Lemon Cream, Clover", label: "Lemon Cream, Clover" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-flower-sweet", displayName: "Alcremie Lemon Cream, Flower", label: "Lemon Cream, Flower" },
  { speciesId: 869, apiName: "alcremie-lemon-cream-ribbon-sweet", displayName: "Alcremie Lemon Cream, Ribbon", label: "Lemon Cream, Ribbon" },
  { speciesId: 869, apiName: "alcremie-salted-cream-strawberry-sweet", displayName: "Alcremie Salted Cream, Strawberry", label: "Salted Cream, Strawberry" },
  { speciesId: 869, apiName: "alcremie-salted-cream-berry-sweet", displayName: "Alcremie Salted Cream, Berry", label: "Salted Cream, Berry" },
  { speciesId: 869, apiName: "alcremie-salted-cream-love-sweet", displayName: "Alcremie Salted Cream, Love", label: "Salted Cream, Love" },
  { speciesId: 869, apiName: "alcremie-salted-cream-star-sweet", displayName: "Alcremie Salted Cream, Star", label: "Salted Cream, Star" },
  { speciesId: 869, apiName: "alcremie-salted-cream-clover-sweet", displayName: "Alcremie Salted Cream, Clover", label: "Salted Cream, Clover" },
  { speciesId: 869, apiName: "alcremie-salted-cream-flower-sweet", displayName: "Alcremie Salted Cream, Flower", label: "Salted Cream, Flower" },
  { speciesId: 869, apiName: "alcremie-salted-cream-ribbon-sweet", displayName: "Alcremie Salted Cream, Ribbon", label: "Salted Cream, Ribbon" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-strawberry-sweet", displayName: "Alcremie Ruby Swirl, Strawberry", label: "Ruby Swirl, Strawberry" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-berry-sweet", displayName: "Alcremie Ruby Swirl, Berry", label: "Ruby Swirl, Berry" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-love-sweet", displayName: "Alcremie Ruby Swirl, Love", label: "Ruby Swirl, Love" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-star-sweet", displayName: "Alcremie Ruby Swirl, Star", label: "Ruby Swirl, Star" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-clover-sweet", displayName: "Alcremie Ruby Swirl, Clover", label: "Ruby Swirl, Clover" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-flower-sweet", displayName: "Alcremie Ruby Swirl, Flower", label: "Ruby Swirl, Flower" },
  { speciesId: 869, apiName: "alcremie-ruby-swirl-ribbon-sweet", displayName: "Alcremie Ruby Swirl, Ribbon", label: "Ruby Swirl, Ribbon" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-strawberry-sweet", displayName: "Alcremie Caramel Swirl, Strawberry", label: "Caramel Swirl, Strawberry" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-berry-sweet", displayName: "Alcremie Caramel Swirl, Berry", label: "Caramel Swirl, Berry" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-love-sweet", displayName: "Alcremie Caramel Swirl, Love", label: "Caramel Swirl, Love" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-star-sweet", displayName: "Alcremie Caramel Swirl, Star", label: "Caramel Swirl, Star" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-clover-sweet", displayName: "Alcremie Caramel Swirl, Clover", label: "Caramel Swirl, Clover" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-flower-sweet", displayName: "Alcremie Caramel Swirl, Flower", label: "Caramel Swirl, Flower" },
  { speciesId: 869, apiName: "alcremie-caramel-swirl-ribbon-sweet", displayName: "Alcremie Caramel Swirl, Ribbon", label: "Caramel Swirl, Ribbon" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-strawberry-sweet", displayName: "Alcremie Rainbow Swirl, Strawberry", label: "Rainbow Swirl, Strawberry" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-berry-sweet", displayName: "Alcremie Rainbow Swirl, Berry", label: "Rainbow Swirl, Berry" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-love-sweet", displayName: "Alcremie Rainbow Swirl, Love", label: "Rainbow Swirl, Love" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-star-sweet", displayName: "Alcremie Rainbow Swirl, Star", label: "Rainbow Swirl, Star" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-clover-sweet", displayName: "Alcremie Rainbow Swirl, Clover", label: "Rainbow Swirl, Clover" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-flower-sweet", displayName: "Alcremie Rainbow Swirl, Flower", label: "Rainbow Swirl, Flower" },
  { speciesId: 869, apiName: "alcremie-rainbow-swirl-ribbon-sweet", displayName: "Alcremie Rainbow Swirl, Ribbon", label: "Rainbow Swirl, Ribbon" },
  { speciesId: 876, apiName: "indeedee-female", displayName: "Indeedee Female", label: "Female" },
  { speciesId: 892, apiName: "urshifu-rapid-strike", displayName: "Urshifu Rapid Strike", label: "Rapid Strike" },
  { speciesId: 893, apiName: "zarude-dada", displayName: "Zarude Dada", label: "Dada" },
  { speciesId: 901, apiName: "ursaluna-bloodmoon", displayName: "Ursaluna Bloodmoon", label: "Bloodmoon" },
  { speciesId: 902, apiName: "basculegion-female", displayName: "Basculegion Female", label: "Female" },
  { speciesId: 905, apiName: "enamorus-therian", displayName: "Enamorus Therian", label: "Therian" },
  { speciesId: 916, apiName: "oinkologne-female", displayName: "Oinkologne Female", label: "Female" },
  { speciesId: 925, apiName: "maushold-family-of-four", displayName: "Maushold Family of 4", label: "Family of 4" },
  { speciesId: 931, apiName: "squawkabilly-blue-plumage", displayName: "Squawkabilly Blue", label: "Blue" },
  { speciesId: 931, apiName: "squawkabilly-yellow-plumage", displayName: "Squawkabilly Yellow", label: "Yellow" },
  { speciesId: 931, apiName: "squawkabilly-white-plumage", displayName: "Squawkabilly White", label: "White" },
  { speciesId: 978, apiName: "tatsugiri-droopy", displayName: "Tatsugiri Droopy", label: "Droopy" },
  { speciesId: 978, apiName: "tatsugiri-stretchy", displayName: "Tatsugiri Stretchy", label: "Stretchy" },
  { speciesId: 982, apiName: "dudunsparce-three-segment", displayName: "Dudunsparce 3 Segment", label: "3 Segment" },
  { speciesId: 999, apiName: "gimmighoul-roaming", displayName: "Gimmighoul Roaming Form", label: "Roaming Form" },
  { speciesId: 1012, apiName: "poltchageist-artisan", displayName: "Poltchageist Artisan", label: "Artisan" },
  { speciesId: 1013, apiName: "sinistcha-masterpiece", displayName: "Sinistcha Masterpiece", label: "Masterpiece" },
];

export const COSMETIC_FORM_KEYS = new Set(
  COSMETIC_FORMS.map((f) => `${f.speciesId}-${f.apiName}`),
);

export const GENDER_DIFFERENCE_FORM_KEYS = new Set(
  COSMETIC_FORMS.filter((f) => f.label === "Female").map(
    (f) => `${f.speciesId}-${f.apiName}`,
  ),
);
