export type GamePokemonLocationOverrides = Record<number, string[]>;

// Temporary curated fallback locations for games that are not yet available in PokeAPI.
// Legends: Z-A and Scarlet/Violet were bootstrapped from Game8 structured Pokedex data on 2026-05-02.
export const GAME_POKEMON_LOCATION_OVERRIDES: Record<string, GamePokemonLocationOverrides> = {
  'legends-za': {
    1: ['Wild Zone 20 (Day and Night)'],
    4: ['Wild Zone 20 (Day and Night)'],
    7: ['Wild Zone 20 (Day and Night)'],
    13: ['Wild Zone 1 (Day and Night)'],
    14: ['Wild Zone 2 (Day and Night)', 'Wild Zone 7 (Day and Night)'],
    15: ['Wild Zone 15 (Day)'],
    16: ['Wild Zone 1 (Day and Night)', 'Wild Zone 5 (Day and Night)'],
    17: ['Wild Zone 5 (Day and Night)'],
    23: ['Wild Zone 4 (Day)', 'Lysandre Labs (Day and Night)'],
    24: ['Wild Zone 10 (Day and Night)', 'Lysandre Labs (Day and Night)'],
    172: ['Wild Zone 1 (Day and Night)'],
    25: ['Wild Zone 3 (Day and Night)'],
    173: ['Wild Zone 19 (Night)'],
    35: ['Wild Zone 19 (Night)'],
    63: ['Wild Zone 5 (Day and Night)'],
    64: ['Wild Zone 9 (Day and Night)'],
    66: ['Wild Zone 8 (Day and Night)', 'Wild Zone 12 (Day and Night)'],
    67: ['Wild Zone 12 (Day and Night)'],
    69: ['Wild Zone 5 (Day and Night)', 'Wild Zone 10 (Day and Night)'],
    70: ['Wild Zone 13 (Day)'],
    79: ['Wild Zone 10 (Day and Night)', 'Wild Zone 11 (Day and Night)'],
    92: ['Wild Zone 4 (Day and Night)', 'Lumiose Sewers (Day and Night)'],
    93: ['Wild Zone 15 (Night)', 'Lumiose Sewers (Day and Night)'],
    95: ['Wild Zone 14 (Day and Night)'],
    115: ['Wild Zone 19 (Day and Night)'],
    120: ['Wild Zone 2 (Night)', 'Wild Zone 10 (Day and Night)'],
    121: ['Wild Zone 16 (Night)'],
    123: ['Wild Zone 13 (Night)'],
    127: ['Wild Zone 13 (Day and Night)'],
    129: ['Wild Zone 2 (Day and Night)', 'Wild Zone 6 (Day and Night)'],
    130: ['Wild Zone 11 (Day and Night)'],
    133: ['Wild Zone 19 (Day and Night)'],
    152: ['Wild Zone 20 (Day and Night)'],
    158: ['Wild Zone 20 (Day and Night)'],
    167: ['Wild Zone 4 (Day and Night)'],
    179: ['Wild Zone 1 (Day and Night)'],
    180: ['Wild Zone 6 (Day and Night)', 'Wild Zone 16 (Day and Night)'],
    214: ['Wild Zone 13 (Day and Night)'],
    227: ['Wild Zone 17 (Day and Night)'],
    228: ['Wild Zone 6 (Day and Night)', 'Lysandre Labs (Day and Night)'],
    229: ['Lysandre Labs (Day and Night)'],
    246: ['Wild Zone 15 (Day and Night)'],
    282: ['Wild Zone 20 (Day and Night)'],
    302: ['Wild Zone 9 (Day and Night)'],
    303: ['Wild Zone 9 (Day and Night)'],
    304: ['Wild Zone 14 (Day and Night)'],
    305: ['Wild Zone 14 (Day and Night)'],
    306: ['Wild Zone 20 (Day and Night)'],
    307: ['Wild Zone 6 (Day)'],
    308: ['Wild Zone 16 (Day)'],
    309: ['Wild Zone 5 (Day and Night)', 'Lysandre Labs (Day and Night)'],
    310: ['Lysandre Labs (Day and Night)'],
    406: ['Wild Zone 2 (Day and Night)'],
    315: ['Wild Zone 7 (Day and Night)'],
    407: ['Wild Zone 20 (Day and Night)'],
    318: ['Wild Zone 10 (Day and Night)'],
    322: ['Wild Zone 8 (Day and Night)'],
    333: ['Wild Zone 6 (Day and Night)', 'Wild Zone 18 (Day)'],
    334: ['Wild Zone 18 (Day)'],
    353: ['Wild Zone 7 (Night)', 'Wild Zone 15 (Night)'],
    361: ['Wild Zone 12 (Day and Night)'],
    371: ['Wild Zone 18 (Day and Night)'],
    374: ['Lysandre Labs (Day and Night)'],
    375: ['Lysandre Labs (Day and Night)'],
    427: ['Wild Zone 6 (Day and Night)'],
    443: ['Wild Zone 8 (Day and Night)'],
    448: ['Wild Zone 20 (Day and Night)'],
    449: ['Wild Zone 7 (Day)'],
    450: ['Wild Zone 20 (Day and Night)'],
    459: ['Wild Zone 12 (Day and Night)'],
    498: ['Wild Zone 20 (Day and Night)'],
    504: ['Wild Zone 2 (Day and Night)', 'Wild Zone 4 (Night)', 'Lumiose Sewers (Day and Night)'],
    505: ['Wild Zone 10 (Day and Night)'],
    529: ['Wild Zone 8 (Day and Night)', 'Wild Zone 14 (Day and Night)'],
    530: ['Wild Zone 14 (Day and Night)'],
    531: ['Wild Zone 7 (Day and Night)', 'Wild Zone 19 (Day and Night)'],
    543: ['Wild Zone 5 (Day and Night)'],
    544: ['Wild Zone 15 (Day)'],
    545: ['Wild Zone 15 (Day)'],
    551: ['Wild Zone 8 (Day and Night)'],
    552: ['Wild Zone 8 (Day and Night)'],
    559: ['Lumiose Sewers (Day and Night)'],
    560: ['Wild Zone 20 (Day and Night)'],
    568: ['Vert Sector 5 (Spawns at level 22 with Bullet Seed. Climb the ladder behind Hotel AZ and head west with Roto Glide, then follow the nets to reach Vert Sector 5. Jump down the eastern corner to find Alpha Trubbish.)'],
    569: ['Wild Zone 20 (Day and Night)'],
    587: ['Wild Zone 14 (Day and Night)'],
    602: ['Wild Zone 10 (Day and Night)'],
    607: ['Lumiose Sewers (Day and Night)'],
    608: ['Wild Zone 17 (Night)'],
    618: ['Wild Zone 11 (Day and Night)'],
    650: ['Wild Zone 17 (Day and Night)'],
    653: ['Wild Zone 18 (Day and Night)'],
    656: ['Wild Zone 16 (Day and Night)'],
    659: ['Wild Zone 1 (Day and Night)', 'Wild Zone 5 (Day and Night)'],
    660: ['Wild Zone 17 (Day and Night)'],
    661: ['Wild Zone 1 (Day and Night)'],
    662: ['Wild Zone 9 (Day and Night)'],
    664: ['Wild Zone 1 (Day and Night)'],
    665: ['Wild Zone 4 (Day)'],
    666: ['Wild Zone 13 (Day)'],
    667: ['Wild Zone 3 (Day and Night)'],
    668: ['Wild Zone 17 (Day and Night)'],
    669: ['Wild Zone 3 (Day)'],
    670: ['Wild Zone 7 (Day and Night)'],
    671: ['Wild Zone 16 (Day)'],
    672: ['Wild Zone 3 (Day and Night)'],
    673: ['Wild Zone 12 (Day and Night)'],
    674: ['Wild Zone 3 (Day and Night)'],
    676: ['Wild Zone 11 (Day and Night)', 'Wild Zone 19 (Day and Night)'],
    677: ['Wild Zone 3 (Day and Night)', 'Wild Zone 9 (Day and Night)'],
    679: ['Wild Zone 4 (Night)', 'Lysandre Labs (Day and Night)'],
    680: ['Lysandre Labs (Day and Night)'],
    686: ['Wild Zone 11 (Day and Night)', 'Lumiose Sewers (Day and Night)'],
    687: ['Wild Zone 20 (Day and Night)'],
    688: ['Wild Zone 2 (Day and Night)', 'Wild Zone 6 (Day and Night)'],
    689: ['Wild Zone 16 (Night)'],
    690: ['Lumiose Sewers (Day and Night)'],
    691: ['Wild Zone 20 (Day and Night)', 'Lumiose Sewers (Day and Night)'],
    692: ['Wild Zone 11 (Day and Night)'],
    694: ['Wild Zone 14 (Day (Clear Skies))'],
    703: ['Wild Zone 9 (Day and Night)'],
    704: ['Lumiose Sewers (Day and Night)'],
    707: ['Wild Zone 17 (Day)', 'Lumiose Sewers (Day and Night)'],
    708: ['Wild Zone 13 (Night)'],
    710: ['Wild Zone 15 (Day and Night)'],
    712: ['Wild Zone 12 (Day and Night)'],
    714: ['Wild Zone 18 (Night)', 'Lumiose Sewers (Day and Night)'],
    715: ['Wild Zone 18 (Night)', 'Lysandre Labs (Day and Night)'],
    780: ['Wild Zone 19 (Day (Morning))'],
    870: ['Wild Zone 16 (Day and Night)'],
    225: ['Wild Zone 12 (Day and Night)'],
    582: ['Wild Zone 7 (Day and Night)', 'Wild Zone 12 (Day and Night)'],
  },
  'scarlet-violet': {
    906: ["Received as a Starter Pokemon outside Nemona's House."],
    909: ["Received as a Starter Pokemon outside Nemona's House."],
    912: ["Received as a Starter Pokemon outside Nemona's House."],
    1007: ['Obtained as a mount near Poco Path Lighthouse, and can be caught in Area Zero after completing the game. (Scarlet Only)'],
    1008: ['Obtained as a mount near Poco Path Lighthouse, and can be caught in Area Zero after completing the game. (Violet Only)'],
    921: ['Poco Path', 'The Great Crater of Paldea', 'South Province (Area One)', 'South Province (Area Three)'],
    915: ['Poco Path', 'Tagtree Thicket', 'The Pokemon League', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'South Province (Area One)', 'South Province (Area Four)', 'South Province (Area Five)'],
    928: ['South Province (Area Two)'],
    25: ['West Province (Area Three)', 'East Province (Area One)', 'South Province (Area Two)', 'South Province (Area Four)'],
    52: ['Dalizapa Passage', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Three)', 'Can only be obtained by completing all interactions with Salvatore.'],
    81: ['East Province (Area Two)', 'East Province (Area Three)'],
    692: ['West Paldean Sea', 'East Paldean Sea', 'North Paldean Sea'],
    279: ['Casseroya Lake', 'West Province (Area One)', 'West Province (Area Two)', 'West Paldean Sea', 'South Province (Area One)', 'South Paldean Sea', 'North Paldean Sea'],
    333: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    242: ['North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)'],
    147: ['Casseroya Lake', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)'],
    246: ['Tagtree Thicket', 'West Province (Area One)', 'East Province (Area Three)', 'South Province (Area Three)', 'South Province (Area Five)', 'South Province (Area Six)', 'Glaseado Mountain'],
    336: ['South Province (Area Three)', 'South Province (Area Five)'],
    448: ['South Province (Area Four)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)'],
    874: ['Asado Desert'],
    415: ['Asado Desert', 'West Province (Area One)', 'East Paldean Sea', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Four)', 'North Province (Area Three)', 'Los Platos'],
    425: ['West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'Glaseado Mountain'],
    54: ['Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'Glaseado Mountain'],
    396: ['Casseroya Lake', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)'],
    187: ['Poco Path', 'South Province (Area One)', 'South Province (Area Two)'],
    548: ['Casseroya Lake', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Six)', 'North Province (Area Three)'],
    761: ['East Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Five)', 'Los Platos'],
    571: ['Available as an early purchase bonus for the Hidden Treasure of Area Zero DLC.', 'Casseroya Lake', 'Tagtree Thicket', 'West Province (Area Three)'],
    840: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area One)', 'South Province (Area Two)', 'South Province (Area Four)', 'North Province (Area One)'],
    856: ['West Province (Area Three)', 'South Province (Area Four)'],
    278: ['West Province (Area One)', 'West Province (Area Two)', 'West Paldean Sea', 'South Province (Area One)', 'South Paldean Sea'],
    211: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea', 'North Paldean Sea'],
    661: ['Poco Path', 'South Province (Area One)', 'South Province (Area Two)'],
    180: ['West Province (Area Two)', 'South Province (Area Six)'],
    669: ['West Province (Area One)', 'East Paldean Sea', 'South Province (Area Four)', 'South Province (Area Five)'],
    833: ['Poco Path', 'Inlet Grotto', 'Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'Cabo Poco', 'Los Platos', 'Cascarrafa'],
    371: ['South Province (Area Five)'],
    48: ['Tagtree Thicket', 'East Province (Area One)', 'East Province (Area Two)', 'North Province (Area One)', 'North Province (Area Two)'],
    839: ['Not known to be found in the wild. Can be evolved from Carkol.'],
    748: ['Regular and Terastal versions can be found along the coast southeast of Levincia.'],
    90: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea', 'North Province (Area One)', 'North Paldean Sea', 'Montenevera'],
    615: ['Glaseado Mountain'],
    94: ['Not known to be found in the wild. Can be evolved from Haunter via trading.'],
    754: ['Casseroya Lake', 'Tagtree Thicket', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    663: ['The Great Crater of Paldea'],
    194: ['South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'Can only be obtained by trading a Paldean Wooper with an NPC in Cascaraffa.'],
    926: ['The Pokemon League', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Six)'],
    975: ['Casseroya Lake', 'North Province (Area One)', 'Glaseado Mountain'],
    129: ['Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'West Paldean Sea', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Paldean Sea', 'North Province (Area Three)', 'Los Platos', 'Montenevera'],
    228: ['South Province (Area One)', 'South Province (Area Four)'],
    58: ['East Province (Area Three)', 'South Province (Area Three)'],
    59: ['North Province (Area Two)'],
    585: ['Dalizapa Passage', 'South Province (Area One)', 'South Province (Area Four)', 'South Province (Area Five)'],
    586: ['Dalizapa Passage', 'South Province (Area One)', 'South Province (Area Four)', 'South Province (Area Five)'],
    229: ['North Province (Area Two)'],
    361: ['Dalizapa Passage', 'North Province (Area One)', 'Glaseado Mountain'],
    130: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea', 'North Paldean Sea'],
    198: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'Asado Desert', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'Los Platos', 'Glaseado Mountain', 'Montenevera'],
    430: ['Dalizapa Passage', 'Casseroya Lake', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    203: ['The Great Crater of Paldea', 'West Province (Area Two)'],
    179: ['South Province (Area Two)'],
    672: ['Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)'],
    673: ['Dalizapa Passage', 'Casseroya Lake', 'Tagtree Thicket', 'The Great Crater of Paldea', 'West Province (Area Three)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain', 'Medali'],
    834: ['Dalizapa Passage', 'Casseroya Lake', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Five)', 'South Province (Area Six)', 'Los Platos', 'Montenevera', 'Medali'],
    878: ['Levincia', 'Dalizapa Passage', 'The Great Crater of Paldea', 'East Province (Area Two)', 'East Province (Area Three)', 'Zapapico'],
    288: ['Dalizapa Passage', 'Casseroya Lake', 'West Province (Area Three)', 'South Province (Area Five)', 'Glaseado Mountain'],
    289: ['Casseroya Lake'],
    331: ['Asado Desert'],
    332: ['Asado Desert'],
    232: ['The Great Crater of Paldea', 'Asado Desert', 'West Province (Area Two)', 'South Province (Area Six)'],
    148: ['Casseroya Lake'],
    204: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)'],
    200: ['Tagtree Thicket', 'West Province (Area One)', 'West Province (Area Three)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'Glaseado Mountain'],
    429: ['Casseroya Lake', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    613: ['Dalizapa Passage', 'North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain'],
    614: ['North Province (Area Three)', 'Glaseado Mountain', 'Montenevera'],
    417: ['West Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    871: ['West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)', 'North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain'],
    700: ['West Province (Area Three)', 'South Province (Area Six)'],
    212: ['Not known to be found in the wild. Can be evolved from Scyther.'],
    604: ['Not known to be found in the wild. Can be evolved from Eelektrik using a Thunder Stone.'],
    858: ['Not known to be found in the wild. Can be evolved from Hattrem.'],
    334: ['Casseroya Lake', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'Alfornada', 'Montenevera', 'Medali'],
    714: ['West Province (Area Two)', 'North Province (Area One)', 'North Province (Area Two)'],
    715: ['North Province (Area One)', 'North Province (Area Two)'],
    875: ['North Province (Area One)', 'North Province (Area Three)', 'North Paldean Sea'],
    55: ['Dalizapa Passage', 'Casseroya Lake', 'The Great Crater of Paldea', 'North Province (Area One)', 'North Province (Area Three)', 'Zapapico', 'Montenevera'],
    635: ['Not known to be found in the wild. Can be evolved from Zweilous. (Scarlet Only)'],
    297: ['West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area Six)', 'North Province (Area Two)', 'Alfornada', 'Zapapico', 'Medali'],
    53: ['West Province (Area Three)'],
    184: ['Casseroya Lake', 'West Province (Area Two)', 'West Province (Area Three)'],
    426: ['West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Six)', 'North Province (Area One)', 'Glaseado Mountain'],
    549: ['Casseroya Lake', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Six)', 'North Province (Area Three)'],
    149: ['Can be found flying around North Province (Area Two).'],
    199: ["Not known to be found in the wild. Can be evolved from Slowpoke via trading with a King's Rock."],
    457: ['West Paldean Sea', 'North Paldean Sea'],
    693: ['South Paldean Sea', 'North Paldean Sea'],
    404: ['South Province (Area Five)'],
    405: ['North Province (Area Two)'],
    26: ['Casseroya Lake', 'The Great Crater of Paldea'],
    296: ['Poco Path', 'The Pokemon League', 'Asado Desert', 'West Province (Area One)', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'Cascarrafa'],
    744: ['Asado Desert', 'West Province (Area One)', 'East Province (Area One)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    819: ['South Province (Area Two)', 'South Province (Area Four)', 'Cortondo', 'Los Platos'],
    854: ['East Province (Area Three)', 'South Province (Area Six)'],
    855: ['Not known to be found in the wild. Can be evolved from Sinistea using a Cracked Pot.'],
    450: ['Asado Desert'],
    479: ['West Province (Area Two)', 'East Province (Area Two)'],
    749: ['Dalizapa Passage', 'Asado Desert', 'West Province (Area One)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'Glaseado Mountain'],
    763: ['Not known to be found in the wild. Can be evolved from a Steenee with Stomp.'],
    133: ['West Province (Area Three)', 'South Province (Area Two)'],
    92: ['Dalizapa Passage', 'Asado Desert', 'West Province (Area One)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    282: ['Glaseado Mountain'],
    183: ['East Province (Area Two)'],
    967: ['Dalizapa Passage', 'West Province (Area Two)', 'East Province (Area Two)'],
    93: ['Dalizapa Passage', 'North Province (Area One)', 'Glaseado Mountain'],
    91: ['West Paldean Sea', 'East Paldean Sea', 'North Paldean Sea'],
    475: ['Dalizapa Passage', 'West Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'Glaseado Mountain'],
    462: ['Can be found circling around the mountains surrounding The Great Crater of Paldea.'],
    248: ['Not known to be found in the wild. Can be evolved from a Pupitar. (Scarlet Only)'],
    136: ['Dalizapa Passage', 'West Province (Area Three)', 'Glaseado Mountain'],
    205: ['Casseroya Lake'],
    181: ['South Province (Area Six)', 'North Province (Area One)'],
    842: ['Not known to be found in the wild. Can be evolved from Applin using a Sweet Apple.'],
    298: ['East Province (Area One)', 'South Province (Area One)', 'South Province (Area Two)'],
    838: ['Dalizapa Passage', 'East Province (Area Three)'],
    113: ['Dalizapa Passage', 'The Great Crater of Paldea', 'Asado Desert', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Two)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    879: ['Casseroya Lake', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    633: ['The Great Crater of Paldea', 'West Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Alfornada', 'Zapapico'],
    603: ['West Province (Area One)', 'West Paldean Sea', 'South Province (Area Four)', 'South Province (Area Six)', 'South Paldean Sea', 'North Paldean Sea'],
    456: ['West Paldean Sea', 'North Paldean Sea'],
    841: ['Not known to be found in the wild. Can be evolved from Applin using a Tart Apple.'],
    662: ['West Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    670: ['The Great Crater of Paldea', 'Asado Desert', 'South Province (Area Five)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)'],
    671: ['North Province (Area Three)'],
    753: ['Tagtree Thicket', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    478: ['West Paldean Sea', 'East Province (Area Two)', 'South Province (Area Five)', 'Montenevera', 'Porto Marinada'],
    362: ['West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Four)'],
    820: ['Dalizapa Passage', 'Tagtree Thicket', 'West Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'Montenevera'],
    440: ['West Province (Area One)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)'],
    857: ['Tagtree Thicket', 'South Province (Area Six)', 'Glaseado Mountain'],
    449: ['Asado Desert'],
    570: ['Will be available via Pokemon HOME on its release in Spring 2023.', 'Tagtree Thicket', 'West Province (Area Three)'],
    189: ['The Great Crater of Paldea', 'West Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)'],
    281: ['West Province (Area Two)', 'East Province (Area Two)', 'Glaseado Mountain'],
    900: ['Will be available via Pokemon HOME on its release in Spring 2023.'],
    745: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'Alfornada', 'Zapapico', 'Glaseado Mountain', 'Montenevera', 'Medali'],
    82: ['Dalizapa Passage', 'Glaseado Mountain'],
    747: ['East Province (Area One)', 'East Province (Area Two)', 'East Paldean Sea'],
    750: ['Dalizapa Passage', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'Glaseado Mountain'],
    231: ['The Great Crater of Paldea', 'Asado Desert', 'West Province (Area One)', 'South Province (Area Four)'],
    172: ['South Province (Area Two)', 'Los Platos'],
    247: ['South Province (Area Six)'],
    280: ['South Province (Area One)'],
    447: ['South Province (Area Four)'],
    837: ['East Province (Area Three)'],
    373: ['Not known to be found in the wild. Can be evolved from Shelgon. (Violet Only)'],
    123: ['Casseroya Lake', 'West Province (Area Three)', 'South Province (Area Four)', 'North Province (Area Two)'],
    372: ['South Province (Area Six)'],
    403: ['South Province (Area Three)'],
    188: ['East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)'],
    287: ['South Province (Area One)', 'South Province (Area Three)', 'South Province (Area Five)'],
    80: ['Casseroya Lake', 'West Province (Area Two)', 'Montenevera'],
    79: ['Dalizapa Passage', 'Casseroya Lake', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)'],
    398: ['Casseroya Lake', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)'],
    397: ['Casseroya Lake', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)'],
    762: ['Dalizapa Passage', 'East Province (Area One)'],
    602: ['West Province (Area One)', 'West Paldean Sea', 'South Province (Area Four)', 'South Province (Area Six)', 'South Paldean Sea', 'North Paldean Sea'],
    49: ['Casseroya Lake', 'Tagtree Thicket', 'The Great Crater of Paldea', 'East Province (Area One)', 'East Province (Area Two)', 'North Province (Area One)', 'North Province (Area Two)'],
    416: ['South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    634: ['The Great Crater of Paldea', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    945: ['Tagtree Thicket'],
    664: ['Poco Path', 'South Province (Area One)'],
    665: ['South Province (Area One)', 'South Province (Area Four)', 'South Province (Area Five)'],
    666: ['East Paldean Sea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)'],
    134: ['Dalizapa Passage', 'Casseroya Lake', 'Tagtree Thicket', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    135: ['Casseroya Lake', 'West Province (Area Three)'],
    196: ['The Great Crater of Paldea', 'North Province (Area Three)', 'Glaseado Mountain'],
    197: ['Dalizapa Passage', 'The Great Crater of Paldea', 'East Province (Area One)', 'South Province (Area Six)', 'North Province (Area Two)', 'Glaseado Mountain'],
    470: ['Casseroya Lake', 'West Province (Area Three)'],
    471: ['Glaseado Mountain'],
    936: ['Evolve from Charcadet by giving 10 Bronzor Fragments to the man in Zapapico. (Scarlet Only)'],
    937: ['Evolve from Charcadet by giving 10 Sinistea Chips to the man in Zapapico. (Violet Only)'],
    950: ['South Province (Area Three)'],
    741: ['East Province (Area One)', 'South Province (Area Three)', 'Can be found in South Province (Area Three) among other places.', 'South Province (Area One)'],
    704: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'Glaseado Mountain'],
    706: ['Not known to be found in the wild. Can be evolved from Sliggoo in overworld rain or fog.'],
    308: ['The Great Crater of Paldea', 'West Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Six)'],
    96: ['South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)'],
    185: ['Casseroya Lake', 'West Province (Area Three)'],
    324: ['Dalizapa Passage', 'East Province (Area Three)', 'Zapapico'],
    286: ['West Province (Area Three)'],
    775: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Four)'],
    192: ['Tagtree Thicket', 'East Paldean Sea', 'South Province (Area Six)', 'North Province (Area Three)'],
    705: ['Casseroya Lake'],
    307: ['The Great Crater of Paldea', 'West Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Six)'],
    97: ['The Great Crater of Paldea'],
    438: ['South Province (Area One)', 'South Province (Area Two)'],
    285: ['West Province (Area Three)', 'South Province (Area Five)'],
    191: ['South Province (Area One)', 'South Province (Area Two)'],
    215: ['Dalizapa Passage', 'The Great Crater of Paldea', 'North Province (Area One)', 'Glaseado Mountain'],
    461: ['The Great Crater of Paldea', 'North Province (Area One)'],
    216: ['East Province (Area One)', 'South Province (Area Five)'],
    217: ['Dalizapa Passage', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    550: ['Can be found in Timeless Woods (River).', 'Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    206: ['Dalizapa Passage', 'The Great Crater of Paldea', 'South Province (Area Four)'],
    960: ['West Province (Area One)', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)'],
    981: ['The Great Crater of Paldea'],
    357: ['Casseroya Lake', 'West Province (Area Three)'],
    39: ['West Province (Area Three)', 'South Province (Area Two)'],
    335: ['South Province (Area Five)'],
    50: ['Poco Path', 'Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Six)'],
    174: ['South Province (Area Two)', 'Los Platos'],
    40: ['North Province (Area One)'],
    51: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'West Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Six)', 'North Province (Area Two)', 'Glaseado Mountain'],
    551: ['Asado Desert'],
    552: ['Can be evolved from Sandile.'],
    459: ['Glaseado Mountain'],
    460: ['Montenevera'],
    553: ['Not known to be found in the wild. Can be evolved from Krokorok.'],
    667: ['Dalizapa Passage', 'East Province (Area One)', 'South Province (Area Five)', 'Glaseado Mountain'],
    88: ['West Province (Area Two)', 'East Province (Area Two)'],
    848: ['South Province (Area Four)', 'South Province (Area Six)'],
    302: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Six)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    668: ['Dalizapa Passage', 'East Province (Area One)', 'South Province (Area Five)', 'Glaseado Mountain'],
    89: ['Can be evolved from Grimer.'],
    849: ['South Province (Area Four)', 'South Province (Area Six)'],
    939: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'West Province (Area Two)', 'North Province (Area Three)', 'Zapapico'],
    453: ['Casseroya Lake', 'West Province (Area Two)', 'South Province (Area Five)'],
    454: ['Casseroya Lake', 'West Province (Area Two)', 'South Province (Area Five)'],
    322: ['The Great Crater of Paldea', 'West Province (Area One)'],
    323: ['The Great Crater of Paldea', 'North Province (Area Two)'],
    437: ['Casseroya Lake', 'West Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    436: ['Asado Desert', 'West Province (Area One)', 'East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)'],
    821: ['Dalizapa Passage', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Three)', 'South Province (Area Five)'],
    822: ['Dalizapa Passage', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Five)'],
    823: ['The Great Crater of Paldea'],
    872: ['Dalizapa Passage', 'Tagtree Thicket', 'West Province (Area Three)', 'Glaseado Mountain'],
    873: ['Casseroya Lake', 'The Great Crater of Paldea', 'Glaseado Mountain'],
    778: ['Tagtree Thicket', 'East Province (Area Two)', 'Glaseado Mountain'],
    971: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area Three)', 'North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain', 'Montenevera'],
    999: ['West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'Transfer from Pokemon GO through Pokemon HOME.'],
    885: ['The Great Crater of Paldea', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'Montenevera'],
    886: ['Casseroya Lake', 'The Great Crater of Paldea', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    887: ['Not known to be found in the wild. Can be evolved from Drakloak. (Violet Only)'],
    702: ['West Province (Area Three)', 'North Province (Area Three)'],
    132: ['West Province (Area Two)', 'West Province (Area Three)'],
    4: ['Can be bred from Charizard.'],
    5: ['Can be evolved from Charmander.'],
    6: ['Available temporarily in a 7-Star Raid Event.'],
    418: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area One)', 'West Province (Area Two)', 'West Paldean Sea', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'East Paldean Sea', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'South Paldean Sea'],
    419: ['Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'West Paldean Sea', 'East Province (Area Three)', 'East Paldean Sea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'North Paldean Sea'],
    907: ['Not known to be found in the wild. Can be evolved from Sprigatito.'],
    908: ['Not known to be found in the wild. Can be evolved from Floragato.'],
    910: ['Not known to be found in the wild. Can be evolved from Fuecoco.'],
    911: ['Not known to be found in the wild. Can be evolved from Crocalor.'],
    913: ['Not known to be found in the wild. Can be evolved from Quaxly.'],
    914: ['Not known to be found in the wild. Can be evolved from Quaxwell.'],
    929: ['Tagtree Thicket', 'East Province (Area Two)', 'North Province (Area Three)', 'Alfornada'],
    973: ['Dalizapa Passage', 'Casseroya Lake', 'The Great Crater of Paldea'],
    917: ['Poco Path', 'Casseroya Lake', 'Tagtree Thicket', 'The Pokemon League', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area One)', 'South Province (Area Four)', 'South Province (Area Five)'],
    128: ['Dalizapa Passage', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)'],
    919: ['West Province (Area One)', 'South Province (Area Three)'],
    920: ['Dalizapa Passage', 'The Great Crater of Paldea', 'Asado Desert', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'Alfornada', 'Zapapico', 'Montenevera', 'Porto Marinada', 'Medali'],
    944: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Two)', 'South Province (Area Four)'],
    916: ['Dalizapa Passage', 'Casseroya Lake', 'Tagtree Thicket', 'The Pokemon League', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Five)'],
    974: ['Dalizapa Passage', 'North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain'],
    932: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    980: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Five)', 'South Province (Area Six)', 'North Province (Area Two)', 'Glaseado Mountain'],
    56: ['West Province (Area One)', 'South Province (Area Five)'],
    57: ['West Province (Area Three)', 'North Province (Area One)', 'North Province (Area Two)'],
    100: ['Dalizapa Passage', 'West Province (Area Three)', 'East Province (Area Three)'],
    101: ['West Province (Area Three)', 'East Province (Area Three)'],
    155: ['Can be bred from Typhlosion.'],
    156: ['Can be evolved from Cyndaquil.'],
    157: ['Available temporarily in a 7-Star Raid Event.'],
    195: ['Not known to be found in the wild. Can be evolved from Wooper.'],
    214: ['Casseroya Lake', 'North Province (Area Two)'],
    225: ['North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain'],
    234: ['South Province (Area Five)'],
    283: ['East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Five)'],
    284: ['The Great Crater of Paldea', 'South Province (Area Four)', 'South Province (Area Five)'],
    316: ['East Province (Area One)', 'South Province (Area Three)'],
    317: ['Casseroya Lake'],
    325: ['South Province (Area Three)'],
    326: ['Dalizapa Passage', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    339: ['Tagtree Thicket', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'North Province (Area One)'],
    340: ['Tagtree Thicket', 'West Province (Area Three)', 'South Province (Area Six)', 'North Province (Area One)', 'Glaseado Mountain'],
    353: ['East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Three)'],
    354: ['South Province (Area Six)', 'Glaseado Mountain'],
    370: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea'],
    401: ['South Province (Area Two)', 'North Province (Area Two)'],
    402: ['North Province (Area One)'],
    422: ['East Province (Area One)', 'South Province (Area Five)', 'North Province (Area One)', 'West Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Six)'],
    423: ['East Province (Area One)', 'South Province (Area Five)', 'North Province (Area One)', 'Casseroya Lake', 'West Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Six)'],
    434: ['West Province (Area Two)', 'South Province (Area Five)'],
    435: ['Casseroya Lake'],
    442: ['Can be found on the Northeast side of Glaseado Mountain.'],
    443: ['The Great Crater of Paldea', 'West Province (Area One)', 'West Province (Area Two)', 'South Province (Area Six)'],
    444: ['Dalizapa Passage', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area Two)', 'Glaseado Mountain'],
    445: ['Can be found flying while climbing the mountains surrounding The Great Crater of Paldea.'],
    501: ['Can be bred from Samurott.'],
    502: ['Can be evolved from Oshawott.'],
    503: ['Available temporarily in a 7-Star Raid Event.'],
    574: ['East Province (Area Three)', 'Glaseado Mountain'],
    575: ['South Province (Area Six)'],
    576: ['South Province (Area Six)'],
    590: ['Tagtree Thicket', 'West Province (Area Three)', 'North Province (Area Two)'],
    591: ['Casseroya Lake', 'North Province (Area Two)'],
    594: ['North Province (Area One)', 'North Province (Area Three)', 'North Paldean Sea'],
    610: ['Dalizapa Passage', 'South Province (Area Five)', 'North Province (Area One)', 'Glaseado Mountain'],
    611: ['Dalizapa Passage', 'South Province (Area Five)', 'North Province (Area One)', 'Glaseado Mountain'],
    612: ['Not known to be found in the wild. Can be evolved from Fraxure.'],
    624: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'East Province (Area Three)', 'South Province (Area Five)'],
    625: ['The Great Crater of Paldea', 'North Province (Area Two)'],
    627: ['Dalizapa Passage', 'Tagtree Thicket', 'West Province (Area One)', 'West Province (Area Three)', 'East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    628: ['The Great Crater of Paldea', 'North Province (Area One)', 'North Province (Area Two)'],
    636: ['Asado Desert'],
    637: ['The Great Crater of Paldea'],
    650: ['Can be bred from Chesnaught.'],
    651: ['Can be evolved from Chespin.'],
    652: ['Available temporarily in a 7-Star Raid Event.'],
    656: ['Can be bred from Greninja.'],
    657: ['Can be evolved from Froakie.'],
    658: ['Available temporarily in a 7-Star Raid Event.'],
    690: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea', 'North Paldean Sea'],
    691: ['North Paldean Sea'],
    701: ['Casseroya Lake', 'The Great Crater of Paldea', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    703: ['Can be found in the Chilling Waterhead caves inside the Oni Mountain.'],
    707: ['Alfornada', 'Glaseado Mountain'],
    712: ['North Paldean Sea', 'Glaseado Mountain'],
    713: ['North Paldean Sea', 'Glaseado Mountain'],
    722: ['Can be bred from Decidueye.'],
    723: ['Can be evolved from Rowlet.'],
    724: ['Available temporarily in a 7-Star Raid Event.'],
    734: ['Dalizapa Passage', 'Asado Desert', 'West Province (Area One)', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)'],
    735: ['Dalizapa Passage', 'Tagtree Thicket', 'Asado Desert', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Five)', 'South Province (Area Six)', 'North Province (Area Three)'],
    739: ['West Province (Area One)', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Three)', 'Glaseado Mountain'],
    740: ['Glaseado Mountain'],
    757: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area One)', 'West Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Six)', 'Glaseado Mountain'],
    758: ['The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'Montenevera'],
    765: ['Casseroya Lake', 'Tagtree Thicket', 'North Province (Area Two)'],
    766: ['Casseroya Lake', 'Tagtree Thicket', 'North Province (Area Two)'],
    769: ['West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)'],
    770: ['Casseroya Lake', 'West Province (Area Two)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area Five)'],
    779: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea'],
    813: ['Can be bred from Cinderace.'],
    814: ['Can be evolved from Scorbunny.'],
    815: ['Available temporarily in a 7-Star Raid Event.'],
    816: ['Can be bred from Inteleon.'],
    817: ['Can be evolved from Sobble.'],
    818: ['Available temporarily in a 7-Star Raid Event.'],
    843: ['Dalizapa Passage', 'Tagtree Thicket', 'Asado Desert', 'East Province (Area Three)'],
    844: ['Not known to be found in the wild. Can be evolved from Silicobra.'],
    846: ['Dalizapa Passage', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)'],
    847: ['Dalizapa Passage', 'West Province (Area Two)', 'West Province (Area Three)', 'West Paldean Sea', 'East Province (Area Three)', 'East Paldean Sea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Three)', 'North Paldean Sea', 'Glaseado Mountain'],
    859: ['Tagtree Thicket'],
    860: ['Tagtree Thicket'],
    861: ['Not known to be found in the wild. Can be evolved from Morgrem.'],
    863: ['Not known to be found in the wild. Can be evolved from Galarian Meowth.'],
    870: ['Asado Desert', 'West Province (Area One)', 'North Province (Area Two)'],
    876: ['North Province (Area One)', 'North Province (Area Two)'],
    982: ['The Great Crater of Paldea'],
    918: ['Casseroya Lake', 'Tagtree Thicket', 'The Pokemon League', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Five)', 'North Province (Area Two)'],
    953: ['Asado Desert'],
    954: ['Not known to be found in the wild. Can be evolved from Rellor.'],
    972: ['Casseroya Lake', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    955: ['Dalizapa Passage', 'Casseroya Lake', 'Tagtree Thicket', 'Asado Desert', 'West Province (Area One)', 'East Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'Glaseado Mountain'],
    956: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'Asado Desert', 'West Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    961: ['West Province (Area Two)', 'East Province (Area Two)', 'North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain'],
    977: ['Casseroya Lake'],
    976: ['Casseroya Lake', 'West Paldean Sea'],
    963: ['West Paldean Sea', 'East Paldean Sea', 'South Paldean Sea', 'North Paldean Sea'],
    930: ['Casseroya Lake', 'Tagtree Thicket', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area Two)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)'],
    951: ['Asado Desert', 'West Province (Area One)'],
    952: ['Dalizapa Passage', 'Casseroya Lake', 'Tagtree Thicket', 'South Province (Area Six)', 'North Province (Area One)', 'Montenevera'],
    938: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Four)', 'South Province (Area Five)', 'Montenevera'],
    965: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area Two)', 'East Province (Area Three)'],
    966: ['East Province (Area Three)', 'North Province (Area One)', 'Glaseado Mountain'],
    968: ['Dalizapa Passage', 'Tagtree Thicket', 'Asado Desert', 'West Paldean Sea', 'East Province (Area Three)', 'East Paldean Sea', 'South Paldean Sea', 'North Paldean Sea'],
    924: ['Artazon', 'Levincia', 'The Pokemon League', 'East Province (Area Two)', 'Zapapico', 'Porto Marinada', 'Medali'],
    925: ['Not known to be found in the wild. Can be evolved from Tandemaus.'],
    996: ['Dalizapa Passage', 'Glaseado Mountain'],
    997: ['North Province (Area Three)'],
    998: ['Not known to be found in the wild. Can be evolved from Arctibax.'],
    978: ['Casseroya Lake'],
    922: ['Dalizapa Passage', 'Tagtree Thicket', 'The Great Crater of Paldea', 'Asado Desert', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Three)', 'Glaseado Mountain'],
    923: ['Not known to be found in the wild. Can be evolved from Pawmo.'],
    940: ['West Province (Area One)', 'West Province (Area Two)', 'East Province (Area Two)', 'South Province (Area One)', 'South Province (Area Four)', 'South Province (Area Six)'],
    941: ['West Paldean Sea', 'East Paldean Sea', 'North Paldean Sea'],
    962: ['West Province (Area One)', 'West Province (Area Three)', 'West Paldean Sea', 'South Province (Area Six)'],
    933: ['Dalizapa Passage', 'Casseroya Lake', 'The Great Crater of Paldea', 'South Province (Area Six)', 'North Province (Area One)', 'North Province (Area Two)', 'North Province (Area Three)', 'Glaseado Mountain'],
    934: ['The Great Crater of Paldea'],
    969: ['Dalizapa Passage', 'The Great Crater of Paldea', 'West Province (Area Two)', 'East Province (Area Three)', 'South Province (Area Six)', 'North Province (Area Two)', 'Glaseado Mountain'],
    970: ['The Great Crater of Paldea'],
    927: ['The Great Crater of Paldea', 'The Pokemon League', 'West Province (Area Three)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Six)'],
    942: ['West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)'],
    943: ['Casseroya Lake', 'West Province (Area Two)', 'West Province (Area Three)', 'South Province (Area Two)', 'South Province (Area Four)'],
    946: ['Dalizapa Passage', 'Asado Desert', 'East Province (Area Three)'],
    947: ['Casseroya Lake', 'North Province (Area One)'],
    1000: ['South Province (Area Two)', 'South Province (Area Three)'],
    984: ['The Great Crater of Paldea'],
    986: ['The Great Crater of Paldea'],
    989: ['The Great Crater of Paldea'],
    985: ['The Great Crater of Paldea'],
    987: ['The Great Crater of Paldea'],
    988: ['The Great Crater of Paldea'],
    1005: ['The Great Crater of Paldea'],
    990: ['The Great Crater of Paldea'],
    994: ['The Great Crater of Paldea'],
    992: ['The Great Crater of Paldea'],
    993: ['The Great Crater of Paldea'],
    995: ['The Great Crater of Paldea'],
    991: ['The Great Crater of Paldea'],
    1006: ['The Great Crater of Paldea'],
    1003: ['Collect all 8 Green Stakes in Casseroya Lake to access the Shrine where Ting-Lu can be found.'],
    1002: ['Collect all 8 Yellow Stakes in the Western side of South Paldea to access the Shrine where Chien-Pao can be found.'],
    1001: ['Collect all 8 Purple Stakes in the Eastern side of South Paldea to access the Shrine where Wo-Chien can be found.'],
    1004: ['Collect all 8 Blue Stakes in Northeast Paldea to access the Shrine where Chi-Yu can be found.'],
    957: ['Asado Desert', 'East Province (Area Two)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)'],
    958: ['Dalizapa Passage', 'North Province (Area One)', 'North Province (Area Two)', 'Glaseado Mountain'],
    959: ['Not known to be found in the wild. Can be evolved from Tinkatuff.'],
    935: ['Dalizapa Passage', 'Tagtree Thicket', 'Asado Desert', 'West Province (Area One)', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Two)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)'],
    948: ['Dalizapa Passage', 'Casseroya Lake', 'Asado Desert', 'West Province (Area Two)', 'West Province (Area Three)', 'East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)', 'South Province (Area One)', 'South Province (Area Three)', 'South Province (Area Four)', 'South Province (Area Five)', 'Glaseado Mountain'],
    949: ['Casseroya Lake'],
    983: ['Not known to be found in the wild. Can be evolved from Bisharp.'],
    979: ['Not known to be found in the wild. Can be evolved from Primeape.'],
    931: ['East Province (Area One)', 'East Province (Area Two)', 'East Province (Area Three)'],
    964: ['Not known to be found in the wild. Can be evolved from Finizen.'],
    1009: ['Available temporarily in a 7-Star Raid Event.'],
    1010: ['Available temporarily in a 7-Star Raid Event.'],
  },
};

export function getGamePokemonLocationOverride(gameId: string, pokemonId: number): string[] {
  return GAME_POKEMON_LOCATION_OVERRIDES[gameId]?.[pokemonId] ?? [];
}

