-- Kitakami Pokédex for Scarlet / Violet: The Teal Mask DLC.
-- Source: Serebii.net /scarletviolet/kitakamipokedex.shtml, verified 2026-05-30.
-- Tracked as scarlet-violet-teal-mask — a DLC sub-dex surfaced as tabs inside
-- the Scarlet/Violet game page, hidden from the main game catalog.

insert into public.game_dex_entries (game_id, species_id, form_name, entry_number)
values
  ('scarlet-violet-teal-mask', 167,  '', 1),   -- Spinarak
  ('scarlet-violet-teal-mask', 168,  '', 2),   -- Ariados
  ('scarlet-violet-teal-mask', 193,  '', 3),   -- Yanma
  ('scarlet-violet-teal-mask', 469,  '', 4),   -- Yanmega
  ('scarlet-violet-teal-mask', 194,  '', 5),   -- Wooper
  ('scarlet-violet-teal-mask', 195,  '', 6),   -- Quagsire
  ('scarlet-violet-teal-mask', 261,  '', 7),   -- Poochyena
  ('scarlet-violet-teal-mask', 262,  '', 8),   -- Mightyena
  ('scarlet-violet-teal-mask', 313,  '', 9),   -- Volbeat
  ('scarlet-violet-teal-mask', 314,  '', 10),  -- Illumise
  ('scarlet-violet-teal-mask', 341,  '', 11),  -- Corphish
  ('scarlet-violet-teal-mask', 342,  '', 12),  -- Crawdaunt
  ('scarlet-violet-teal-mask', 540,  '', 13),  -- Sewaddle
  ('scarlet-violet-teal-mask', 541,  '', 14),  -- Swadloon
  ('scarlet-violet-teal-mask', 542,  '', 15),  -- Leavanny
  ('scarlet-violet-teal-mask', 742,  '', 16),  -- Cutiefly
  ('scarlet-violet-teal-mask', 743,  '', 17),  -- Ribombee
  ('scarlet-violet-teal-mask', 23,   '', 18),  -- Ekans
  ('scarlet-violet-teal-mask', 24,   '', 19),  -- Arbok
  ('scarlet-violet-teal-mask', 172,  '', 20),  -- Pichu
  ('scarlet-violet-teal-mask', 25,   '', 21),  -- Pikachu
  ('scarlet-violet-teal-mask', 26,   '', 22),  -- Raichu
  ('scarlet-violet-teal-mask', 69,   '', 23),  -- Bellsprout
  ('scarlet-violet-teal-mask', 70,   '', 24),  -- Weepinbell
  ('scarlet-violet-teal-mask', 71,   '', 25),  -- Victreebel
  ('scarlet-violet-teal-mask', 161,  '', 26),  -- Sentret
  ('scarlet-violet-teal-mask', 162,  '', 27),  -- Furret
  ('scarlet-violet-teal-mask', 396,  '', 28),  -- Starly
  ('scarlet-violet-teal-mask', 397,  '', 29),  -- Staravia
  ('scarlet-violet-teal-mask', 398,  '', 30),  -- Staraptor
  ('scarlet-violet-teal-mask', 753,  '', 31),  -- Fomantis
  ('scarlet-violet-teal-mask', 754,  '', 32),  -- Lurantis
  ('scarlet-violet-teal-mask', 840,  '', 33),  -- Applin
  ('scarlet-violet-teal-mask', 841,  '', 34),  -- Flapple
  ('scarlet-violet-teal-mask', 842,  '', 35),  -- Appletun
  ('scarlet-violet-teal-mask', 1011, '', 36),  -- Dipplin
  ('scarlet-violet-teal-mask', 37,   '', 37),  -- Vulpix
  ('scarlet-violet-teal-mask', 38,   '', 38),  -- Ninetales
  ('scarlet-violet-teal-mask', 60,   '', 39),  -- Poliwag
  ('scarlet-violet-teal-mask', 61,   '', 40),  -- Poliwhirl
  ('scarlet-violet-teal-mask', 62,   '', 41),  -- Poliwrath
  ('scarlet-violet-teal-mask', 186,  '', 42),  -- Politoed
  ('scarlet-violet-teal-mask', 129,  '', 43),  -- Magikarp
  ('scarlet-violet-teal-mask', 130,  '', 44),  -- Gyarados
  ('scarlet-violet-teal-mask', 163,  '', 45),  -- Hoothoot
  ('scarlet-violet-teal-mask', 164,  '', 46),  -- Noctowl
  ('scarlet-violet-teal-mask', 190,  '', 47),  -- Aipom
  ('scarlet-violet-teal-mask', 424,  '', 48),  -- Ambipom
  ('scarlet-violet-teal-mask', 214,  '', 49),  -- Heracross
  ('scarlet-violet-teal-mask', 220,  '', 50),  -- Swinub
  ('scarlet-violet-teal-mask', 221,  '', 51),  -- Piloswine
  ('scarlet-violet-teal-mask', 473,  '', 52),  -- Mamoswine
  ('scarlet-violet-teal-mask', 234,  '', 53),  -- Stantler
  ('scarlet-violet-teal-mask', 273,  '', 54),  -- Seedot
  ('scarlet-violet-teal-mask', 274,  '', 55),  -- Nuzleaf
  ('scarlet-violet-teal-mask', 275,  '', 56),  -- Shiftry
  ('scarlet-violet-teal-mask', 280,  '', 57),  -- Ralts
  ('scarlet-violet-teal-mask', 281,  '', 58),  -- Kirlia
  ('scarlet-violet-teal-mask', 282,  '', 59),  -- Gardevoir
  ('scarlet-violet-teal-mask', 475,  '', 60),  -- Gallade
  ('scarlet-violet-teal-mask', 401,  '', 61),  -- Kricketot
  ('scarlet-violet-teal-mask', 402,  '', 62),  -- Kricketune
  ('scarlet-violet-teal-mask', 417,  '', 63),  -- Pachirisu
  ('scarlet-violet-teal-mask', 447,  '', 64),  -- Riolu
  ('scarlet-violet-teal-mask', 448,  '', 65),  -- Lucario
  ('scarlet-violet-teal-mask', 548,  '', 66),  -- Petilil
  ('scarlet-violet-teal-mask', 549,  '', 67),  -- Lilligant
  ('scarlet-violet-teal-mask', 708,  '', 68),  -- Phantump
  ('scarlet-violet-teal-mask', 709,  '', 69),  -- Trevenant
  ('scarlet-violet-teal-mask', 744,  '', 70),  -- Rockruff
  ('scarlet-violet-teal-mask', 745,  '', 71),  -- Lycanroc
  ('scarlet-violet-teal-mask', 819,  '', 72),  -- Skwovet
  ('scarlet-violet-teal-mask', 820,  '', 73),  -- Greedent
  ('scarlet-violet-teal-mask', 948,  '', 74),  -- Toedscool
  ('scarlet-violet-teal-mask', 949,  '', 75),  -- Toedscruel
  ('scarlet-violet-teal-mask', 1012, '', 76),  -- Poltchageist
  ('scarlet-violet-teal-mask', 1013, '', 77),  -- Sinistcha
  ('scarlet-violet-teal-mask', 58,   '', 78),  -- Growlithe
  ('scarlet-violet-teal-mask', 59,   '', 79),  -- Arcanine
  ('scarlet-violet-teal-mask', 74,   '', 80),  -- Geodude
  ('scarlet-violet-teal-mask', 75,   '', 81),  -- Graveler
  ('scarlet-violet-teal-mask', 76,   '', 82),  -- Golem
  ('scarlet-violet-teal-mask', 438,  '', 83),  -- Bonsly
  ('scarlet-violet-teal-mask', 185,  '', 84),  -- Sudowoodo
  ('scarlet-violet-teal-mask', 532,  '', 85),  -- Timburr
  ('scarlet-violet-teal-mask', 533,  '', 86),  -- Gurdurr
  ('scarlet-violet-teal-mask', 534,  '', 87),  -- Conkeldurr
  ('scarlet-violet-teal-mask', 714,  '', 88),  -- Noibat
  ('scarlet-violet-teal-mask', 715,  '', 89),  -- Noivern
  ('scarlet-violet-teal-mask', 846,  '', 90),  -- Arrokuda
  ('scarlet-violet-teal-mask', 847,  '', 91),  -- Barraskewda
  ('scarlet-violet-teal-mask', 856,  '', 92),  -- Hatenna
  ('scarlet-violet-teal-mask', 857,  '', 93),  -- Hattrem
  ('scarlet-violet-teal-mask', 858,  '', 94),  -- Hatterene
  ('scarlet-violet-teal-mask', 877,  '', 95),  -- Morpeko
  ('scarlet-violet-teal-mask', 968,  '', 96),  -- Orthworm
  ('scarlet-violet-teal-mask', 924,  '', 97),  -- Tandemaus
  ('scarlet-violet-teal-mask', 925,  '', 98),  -- Maushold
  ('scarlet-violet-teal-mask', 56,   '', 99),  -- Mankey
  ('scarlet-violet-teal-mask', 57,   '', 100), -- Primeape
  ('scarlet-violet-teal-mask', 979,  '', 101), -- Annihilape
  ('scarlet-violet-teal-mask', 446,  '', 102), -- Munchlax
  ('scarlet-violet-teal-mask', 143,  '', 103), -- Snorlax
  ('scarlet-violet-teal-mask', 270,  '', 104), -- Lotad
  ('scarlet-violet-teal-mask', 271,  '', 105), -- Lombre
  ('scarlet-violet-teal-mask', 272,  '', 106), -- Ludicolo
  ('scarlet-violet-teal-mask', 299,  '', 107), -- Nosepass
  ('scarlet-violet-teal-mask', 476,  '', 108), -- Probopass
  ('scarlet-violet-teal-mask', 403,  '', 109), -- Shinx
  ('scarlet-violet-teal-mask', 404,  '', 110), -- Luxio
  ('scarlet-violet-teal-mask', 405,  '', 111), -- Luxray
  ('scarlet-violet-teal-mask', 736,  '', 112), -- Grubbin
  ('scarlet-violet-teal-mask', 737,  '', 113), -- Charjabug
  ('scarlet-violet-teal-mask', 738,  '', 114), -- Vikavolt
  ('scarlet-violet-teal-mask', 741,  '', 115), -- Oricorio
  ('scarlet-violet-teal-mask', 27,   '', 116), -- Sandshrew
  ('scarlet-violet-teal-mask', 28,   '', 117), -- Sandslash
  ('scarlet-violet-teal-mask', 92,   '', 118), -- Gastly
  ('scarlet-violet-teal-mask', 93,   '', 119), -- Haunter
  ('scarlet-violet-teal-mask', 94,   '', 120), -- Gengar
  ('scarlet-violet-teal-mask', 207,  '', 121), -- Gligar
  ('scarlet-violet-teal-mask', 472,  '', 122), -- Gliscor
  ('scarlet-violet-teal-mask', 228,  '', 123), -- Houndour
  ('scarlet-violet-teal-mask', 229,  '', 124), -- Houndoom
  ('scarlet-violet-teal-mask', 325,  '', 125), -- Spoink
  ('scarlet-violet-teal-mask', 326,  '', 126), -- Grumpig
  ('scarlet-violet-teal-mask', 629,  '', 127), -- Vullaby
  ('scarlet-violet-teal-mask', 630,  '', 128), -- Mandibuzz
  ('scarlet-violet-teal-mask', 749,  '', 129), -- Mudbray
  ('scarlet-violet-teal-mask', 750,  '', 130), -- Mudsdale
  ('scarlet-violet-teal-mask', 782,  '', 131), -- Jangmo-o
  ('scarlet-violet-teal-mask', 783,  '', 132), -- Hakamo-o
  ('scarlet-violet-teal-mask', 784,  '', 133), -- Kommo-o
  ('scarlet-violet-teal-mask', 962,  '', 134), -- Bombirdier
  ('scarlet-violet-teal-mask', 109,  '', 135), -- Koffing
  ('scarlet-violet-teal-mask', 110,  '', 136), -- Weezing
  ('scarlet-violet-teal-mask', 619,  '', 137), -- Mienfoo
  ('scarlet-violet-teal-mask', 620,  '', 138), -- Mienshao
  ('scarlet-violet-teal-mask', 355,  '', 139), -- Duskull
  ('scarlet-violet-teal-mask', 356,  '', 140), -- Dusclops
  ('scarlet-violet-teal-mask', 477,  '', 141), -- Dusknoir
  ('scarlet-violet-teal-mask', 433,  '', 142), -- Chingling
  ('scarlet-violet-teal-mask', 358,  '', 143), -- Chimecho
  ('scarlet-violet-teal-mask', 218,  '', 144), -- Slugma
  ('scarlet-violet-teal-mask', 219,  '', 145), -- Magcargo
  ('scarlet-violet-teal-mask', 607,  '', 146), -- Litwick
  ('scarlet-violet-teal-mask', 608,  '', 147), -- Lampent
  ('scarlet-violet-teal-mask', 609,  '', 148), -- Chandelure
  ('scarlet-violet-teal-mask', 283,  '', 149), -- Surskit
  ('scarlet-violet-teal-mask', 284,  '', 150), -- Masquerain
  ('scarlet-violet-teal-mask', 173,  '', 151), -- Cleffa
  ('scarlet-violet-teal-mask', 35,   '', 152), -- Clefairy
  ('scarlet-violet-teal-mask', 36,   '', 153), -- Clefable
  ('scarlet-violet-teal-mask', 436,  '', 154), -- Bronzor
  ('scarlet-violet-teal-mask', 437,  '', 155), -- Bronzong
  ('scarlet-violet-teal-mask', 969,  '', 156), -- Glimmet
  ('scarlet-violet-teal-mask', 970,  '', 157), -- Glimmora
  ('scarlet-violet-teal-mask', 349,  '', 158), -- Feebas
  ('scarlet-violet-teal-mask', 350,  '', 159), -- Milotic
  ('scarlet-violet-teal-mask', 206,  '', 160), -- Dunsparce
  ('scarlet-violet-teal-mask', 982,  '', 161), -- Dudunsparce
  ('scarlet-violet-teal-mask', 339,  '', 162), -- Barboach
  ('scarlet-violet-teal-mask', 340,  '', 163), -- Whiscash
  ('scarlet-violet-teal-mask', 443,  '', 164), -- Gible
  ('scarlet-violet-teal-mask', 444,  '', 165), -- Gabite
  ('scarlet-violet-teal-mask', 445,  '', 166), -- Garchomp
  ('scarlet-violet-teal-mask', 703,  '', 167), -- Carbink
  ('scarlet-violet-teal-mask', 757,  '', 168), -- Salandit
  ('scarlet-violet-teal-mask', 758,  '', 169), -- Salazzle
  ('scarlet-violet-teal-mask', 215,  '', 170), -- Sneasel
  ('scarlet-violet-teal-mask', 461,  '', 171), -- Weavile
  ('scarlet-violet-teal-mask', 361,  '', 172), -- Snorunt
  ('scarlet-violet-teal-mask', 362,  '', 173), -- Glalie
  ('scarlet-violet-teal-mask', 478,  '', 174), -- Froslass
  ('scarlet-violet-teal-mask', 602,  '', 175), -- Tynamo
  ('scarlet-violet-teal-mask', 603,  '', 176), -- Eelektrik
  ('scarlet-violet-teal-mask', 604,  '', 177), -- Eelektross
  ('scarlet-violet-teal-mask', 704,  '', 178), -- Goomy
  ('scarlet-violet-teal-mask', 705,  '', 179), -- Sliggoo
  ('scarlet-violet-teal-mask', 706,  '', 180), -- Goodra
  ('scarlet-violet-teal-mask', 580,  '', 181), -- Ducklett
  ('scarlet-violet-teal-mask', 581,  '', 182), -- Swanna
  ('scarlet-violet-teal-mask', 833,  '', 183), -- Chewtle
  ('scarlet-violet-teal-mask', 834,  '', 184), -- Drednaw
  ('scarlet-violet-teal-mask', 845,  '', 185), -- Cramorant
  ('scarlet-violet-teal-mask', 624,  '', 186), -- Pawniard
  ('scarlet-violet-teal-mask', 625,  '', 187), -- Bisharp
  ('scarlet-violet-teal-mask', 983,  '', 188), -- Kingambit
  ('scarlet-violet-teal-mask', 778,  '', 189), -- Mimikyu
  ('scarlet-violet-teal-mask', 859,  '', 190), -- Impidimp
  ('scarlet-violet-teal-mask', 860,  '', 191), -- Morgrem
  ('scarlet-violet-teal-mask', 861,  '', 192), -- Grimmsnarl
  ('scarlet-violet-teal-mask', 876,  '', 193), -- Indeedee
  ('scarlet-violet-teal-mask', 550,  '', 194), -- Basculin
  ('scarlet-violet-teal-mask', 902,  '', 195), -- Basculegion
  ('scarlet-violet-teal-mask', 901,  '', 196), -- Ursaluna
  ('scarlet-violet-teal-mask', 1014, '', 197), -- Okidogi
  ('scarlet-violet-teal-mask', 1015, '', 198), -- Munkidori
  ('scarlet-violet-teal-mask', 1016, '', 199), -- Fezandipiti
  ('scarlet-violet-teal-mask', 1017, '', 200)  -- Ogerpon
on conflict (game_id, species_id, form_name)
do update set entry_number = excluded.entry_number;
