-- Living Pokedex Tracker baseline schema.
-- Apply this to a Supabase project before running the Python seeder.

create table if not exists public.species (
  id integer primary key,
  name text not null,
  generation integer not null check (generation between 1 and 9)
);

create table if not exists public.living_dex_entries (
  id integer generated by default as identity primary key,
  species_id integer not null references public.species(id) on delete cascade,
  form_name text,
  display_name text not null,
  sprite_url text not null,
  shiny_sprite_url text not null,
  is_regional_form boolean not null default false,
  region_label text,
  sort_order integer not null,
  types jsonb not null default '[]'::jsonb,
  stats jsonb not null default '{}'::jsonb,
  height integer,
  weight integer
);

create index if not exists ix_living_dex_entries_species_id
  on public.living_dex_entries (species_id);

create index if not exists ix_living_dex_entries_sort_order
  on public.living_dex_entries (sort_order);

create table if not exists public.game_dex_entries (
  game_id text not null,
  species_id integer not null references public.species(id) on delete cascade,
  form_name text not null default '',
  entry_number integer,
  primary key (game_id, species_id, form_name)
);

create index if not exists ix_game_dex_entries_game_id
  on public.game_dex_entries (game_id);

create index if not exists ix_game_dex_entries_species_id
  on public.game_dex_entries (species_id);

create table if not exists public.encounters (
  id integer generated by default as identity primary key,
  species_id integer not null references public.species(id) on delete cascade,
  form_name text,
  game_id text not null,
  location_name text not null,
  constraint encounters_unique_location unique nulls not distinct (
    species_id,
    form_name,
    game_id,
    location_name
  )
);

create index if not exists ix_encounters_species_id
  on public.encounters (species_id);

create index if not exists ix_encounters_game_id
  on public.encounters (game_id);

create table if not exists public.pokedex (
  user_id uuid not null references auth.users(id) on delete cascade,
  species_id integer not null,
  form_name text,
  owned boolean not null default false,
  shiny_owned boolean not null default false,
  in_home boolean not null default false,
  method text check (
    method is null
    or method in ('caught', 'bred', 'hatched', 'transferred', 'event')
  ),
  shiny_method text check (
    shiny_method is null
    or shiny_method in (
      'masuda',
      'sos-chain',
      'poke-radar',
      'dex-nav',
      'soft-reset',
      'outbreak',
      'random'
    )
  ),
  shiny_game text,
  updated_at timestamptz not null default now(),
  constraint pokedex_user_species_form_unique unique nulls not distinct (
    user_id,
    species_id,
    form_name
  )
);

create index if not exists ix_pokedex_user_id
  on public.pokedex (user_id);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  available_games jsonb not null default '{}'::jsonb,
  game_dex_progress jsonb not null default '{}'::jsonb,
  shiny_game_dex_progress jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_pokedex_updated_at on public.pokedex;
create trigger set_pokedex_updated_at
before update on public.pokedex
for each row execute function public.set_updated_at();

drop trigger if exists set_user_settings_updated_at on public.user_settings;
create trigger set_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_updated_at();

alter table public.species enable row level security;
alter table public.living_dex_entries enable row level security;
alter table public.game_dex_entries enable row level security;
alter table public.encounters enable row level security;
alter table public.pokedex enable row level security;
alter table public.user_settings enable row level security;

drop policy if exists "Reference data is publicly readable" on public.species;
create policy "Reference data is publicly readable"
on public.species for select
using (true);

drop policy if exists "Living dex entries are publicly readable" on public.living_dex_entries;
create policy "Living dex entries are publicly readable"
on public.living_dex_entries for select
using (true);

drop policy if exists "Game dex entries are publicly readable" on public.game_dex_entries;
create policy "Game dex entries are publicly readable"
on public.game_dex_entries for select
using (true);

drop policy if exists "Encounters are publicly readable" on public.encounters;
create policy "Encounters are publicly readable"
on public.encounters for select
using (true);

drop policy if exists "Users can read their pokedex rows" on public.pokedex;
create policy "Users can read their pokedex rows"
on public.pokedex for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their pokedex rows" on public.pokedex;
create policy "Users can insert their pokedex rows"
on public.pokedex for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their pokedex rows" on public.pokedex;
create policy "Users can update their pokedex rows"
on public.pokedex for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their pokedex rows" on public.pokedex;
create policy "Users can delete their pokedex rows"
on public.pokedex for delete
using (auth.uid() = user_id);

drop policy if exists "Users can read their settings" on public.user_settings;
create policy "Users can read their settings"
on public.user_settings for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their settings" on public.user_settings;
create policy "Users can insert their settings"
on public.user_settings for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their settings" on public.user_settings;
create policy "Users can update their settings"
on public.user_settings for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
