-- Source-aware spawn data for richer encounter guidance and future maps.

create table if not exists public.spawn_locations (
  id bigint generated by default as identity primary key,
  game_id text not null,
  version_ids text[] not null default '{}',
  species_id integer not null references public.species(id) on delete cascade,
  form_name text,
  pokemon_form_identifier text,
  location_identifier text not null,
  location_name text not null,
  location_area_identifier text not null,
  location_area_name text not null,
  region_area_identifier text,
  encounter_method_identifier text not null,
  encounter_method_name text not null,
  levels text,
  alpha_levels text,
  tera_raid_star_level text,
  time_labels text[] not null default '{}',
  weather_labels text[] not null default '{}',
  terrain_labels text[] not null default '{}',
  rates jsonb not null default '{}'::jsonb,
  notes text,
  source text not null check (source in ('pokeapi', 'pokedb', 'manual')),
  source_key text not null,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint spawn_locations_source_key_unique unique (source, source_key)
);

create index if not exists ix_spawn_locations_game_id
  on public.spawn_locations (game_id);

create index if not exists ix_spawn_locations_species_id
  on public.spawn_locations (species_id);

create index if not exists ix_spawn_locations_location_identifier
  on public.spawn_locations (location_identifier);

create index if not exists ix_spawn_locations_location_area_identifier
  on public.spawn_locations (location_area_identifier);

create table if not exists public.map_location_outlines (
  id bigint generated by default as identity primary key,
  game_id text not null,
  location_identifier text not null,
  location_name text not null,
  region_area_identifier text,
  layer integer,
  outline_type text not null,
  points jsonb not null,
  map_part_image text,
  source text not null check (source in ('pokedb', 'manual')),
  source_key text not null,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint map_location_outlines_source_key_unique unique (source, source_key)
);

create index if not exists ix_map_location_outlines_game_id
  on public.map_location_outlines (game_id);

create index if not exists ix_map_location_outlines_location_identifier
  on public.map_location_outlines (location_identifier);

drop trigger if exists set_spawn_locations_updated_at on public.spawn_locations;
create trigger set_spawn_locations_updated_at
before update on public.spawn_locations
for each row execute function public.set_updated_at();

drop trigger if exists set_map_location_outlines_updated_at on public.map_location_outlines;
create trigger set_map_location_outlines_updated_at
before update on public.map_location_outlines
for each row execute function public.set_updated_at();

alter table public.spawn_locations enable row level security;
alter table public.map_location_outlines enable row level security;

drop policy if exists "Spawn locations are publicly readable" on public.spawn_locations;
create policy "Spawn locations are publicly readable"
on public.spawn_locations for select
using (true);

drop policy if exists "Map location outlines are publicly readable" on public.map_location_outlines;
create policy "Map location outlines are publicly readable"
on public.map_location_outlines for select
using (true);
