-- Isle of Armor Pokédex for Sword / Shield: The Isle of Armor DLC.
-- Source: PokéAPI /pokedex/isle-of-armor, verified 2026-07-03.
-- Tracked as swsh-isle-of-armor — a DLC sub-dex surfaced as tabs inside
-- the Sword/Shield game page, hidden from the main game catalog.

insert into public.game_dex_entries (game_id, species_id, form_name, entry_number)
values
  ('swsh-isle-of-armor', 79,  '', 1),    -- Slowpoke
  ('swsh-isle-of-armor', 80,  '', 2),    -- Slowbro
  ('swsh-isle-of-armor', 199, '', 3),    -- Slowking
  ('swsh-isle-of-armor', 427, '', 4),    -- Buneary
  ('swsh-isle-of-armor', 428, '', 5),    -- Lopunny
  ('swsh-isle-of-armor', 440, '', 6),    -- Happiny
  ('swsh-isle-of-armor', 113, '', 7),    -- Chansey
  ('swsh-isle-of-armor', 242, '', 8),    -- Blissey
  ('swsh-isle-of-armor', 819, '', 9),    -- Skwovet
  ('swsh-isle-of-armor', 820, '', 10),   -- Greedent
  ('swsh-isle-of-armor', 174, '', 11),   -- Igglybuff
  ('swsh-isle-of-armor', 39,  '', 12),   -- Jigglypuff
  ('swsh-isle-of-armor', 40,  '', 13),   -- Wigglytuff
  ('swsh-isle-of-armor', 824, '', 14),   -- Blipbug
  ('swsh-isle-of-armor', 825, '', 15),   -- Dottler
  ('swsh-isle-of-armor', 826, '', 16),   -- Orbeetle
  ('swsh-isle-of-armor', 753, '', 17),   -- Fomantis
  ('swsh-isle-of-armor', 754, '', 18),   -- Lurantis
  ('swsh-isle-of-armor', 840, '', 19),   -- Applin
  ('swsh-isle-of-armor', 841, '', 20),   -- Flapple
  ('swsh-isle-of-armor', 842, '', 21),   -- Appletun
  ('swsh-isle-of-armor', 661, '', 22),   -- Fletchling
  ('swsh-isle-of-armor', 662, '', 23),   -- Fletchinder
  ('swsh-isle-of-armor', 663, '', 24),   -- Talonflame
  ('swsh-isle-of-armor', 403, '', 25),   -- Shinx
  ('swsh-isle-of-armor', 404, '', 26),   -- Luxio
  ('swsh-isle-of-armor', 405, '', 27),   -- Luxray
  ('swsh-isle-of-armor', 707, '', 28),   -- Klefki
  ('swsh-isle-of-armor', 624, '', 29),   -- Pawniard
  ('swsh-isle-of-armor', 625, '', 30),   -- Bisharp
  ('swsh-isle-of-armor', 63,  '', 31),   -- Abra
  ('swsh-isle-of-armor', 64,  '', 32),   -- Kadabra
  ('swsh-isle-of-armor', 65,  '', 33),   -- Alakazam
  ('swsh-isle-of-armor', 280, '', 34),   -- Ralts
  ('swsh-isle-of-armor', 281, '', 35),   -- Kirlia
  ('swsh-isle-of-armor', 282, '', 36),   -- Gardevoir
  ('swsh-isle-of-armor', 475, '', 37),   -- Gallade
  ('swsh-isle-of-armor', 98,  '', 38),   -- Krabby
  ('swsh-isle-of-armor', 99,  '', 39),   -- Kingler
  ('swsh-isle-of-armor', 72,  '', 40),   -- Tentacool
  ('swsh-isle-of-armor', 73,  '', 41),   -- Tentacruel
  ('swsh-isle-of-armor', 129, '', 42),   -- Magikarp
  ('swsh-isle-of-armor', 130, '', 43),   -- Gyarados
  ('swsh-isle-of-armor', 223, '', 44),   -- Remoraid
  ('swsh-isle-of-armor', 224, '', 45),   -- Octillery
  ('swsh-isle-of-armor', 458, '', 46),   -- Mantyke
  ('swsh-isle-of-armor', 226, '', 47),   -- Mantine
  ('swsh-isle-of-armor', 278, '', 48),   -- Wingull
  ('swsh-isle-of-armor', 279, '', 49),   -- Pelipper
  ('swsh-isle-of-armor', 451, '', 50),   -- Skorupi
  ('swsh-isle-of-armor', 452, '', 51),   -- Drapion
  ('swsh-isle-of-armor', 206, '', 52),   -- Dunsparce
  ('swsh-isle-of-armor', 626, '', 53),   -- Bouffalant
  ('swsh-isle-of-armor', 108, '', 54),   -- Lickitung
  ('swsh-isle-of-armor', 463, '', 55),   -- Lickilicky
  ('swsh-isle-of-armor', 833, '', 56),   -- Chewtle
  ('swsh-isle-of-armor', 834, '', 57),   -- Drednaw
  ('swsh-isle-of-armor', 194, '', 58),   -- Wooper
  ('swsh-isle-of-armor', 195, '', 59),   -- Quagsire
  ('swsh-isle-of-armor', 704, '', 60),   -- Goomy
  ('swsh-isle-of-armor', 705, '', 61),   -- Sliggoo
  ('swsh-isle-of-armor', 706, '', 62),   -- Goodra
  ('swsh-isle-of-armor', 621, '', 63),   -- Druddigon
  ('swsh-isle-of-armor', 616, '', 64),   -- Shelmet
  ('swsh-isle-of-armor', 617, '', 65),   -- Accelgor
  ('swsh-isle-of-armor', 588, '', 66),   -- Karrablast
  ('swsh-isle-of-armor', 589, '', 67),   -- Escavalier
  ('swsh-isle-of-armor', 1,   '', 68),   -- Bulbasaur
  ('swsh-isle-of-armor', 2,   '', 69),   -- Ivysaur
  ('swsh-isle-of-armor', 3,   '', 70),   -- Venusaur
  ('swsh-isle-of-armor', 7,   '', 71),   -- Squirtle
  ('swsh-isle-of-armor', 8,   '', 72),   -- Wartortle
  ('swsh-isle-of-armor', 9,   '', 73),   -- Blastoise
  ('swsh-isle-of-armor', 543, '', 74),   -- Venipede
  ('swsh-isle-of-armor', 544, '', 75),   -- Whirlipede
  ('swsh-isle-of-armor', 545, '', 76),   -- Scolipede
  ('swsh-isle-of-armor', 590, '', 77),   -- Foongus
  ('swsh-isle-of-armor', 591, '', 78),   -- Amoonguss
  ('swsh-isle-of-armor', 764, '', 79),   -- Comfey
  ('swsh-isle-of-armor', 114, '', 80),   -- Tangela
  ('swsh-isle-of-armor', 465, '', 81),   -- Tangrowth
  ('swsh-isle-of-armor', 453, '', 82),   -- Croagunk
  ('swsh-isle-of-armor', 454, '', 83),   -- Toxicroak
  ('swsh-isle-of-armor', 172, '', 84),   -- Pichu
  ('swsh-isle-of-armor', 25,  '', 85),   -- Pikachu
  ('swsh-isle-of-armor', 26,  '', 86),   -- Raichu
  ('swsh-isle-of-armor', 570, '', 87),   -- Zorua
  ('swsh-isle-of-armor', 571, '', 88),   -- Zoroark
  ('swsh-isle-of-armor', 765, '', 89),   -- Oranguru
  ('swsh-isle-of-armor', 766, '', 90),   -- Passimian
  ('swsh-isle-of-armor', 341, '', 91),   -- Corphish
  ('swsh-isle-of-armor', 342, '', 92),   -- Crawdaunt
  ('swsh-isle-of-armor', 845, '', 93),   -- Cramorant
  ('swsh-isle-of-armor', 118, '', 94),   -- Goldeen
  ('swsh-isle-of-armor', 119, '', 95),   -- Seaking
  ('swsh-isle-of-armor', 846, '', 96),   -- Arrokuda
  ('swsh-isle-of-armor', 847, '', 97),   -- Barraskewda
  ('swsh-isle-of-armor', 120, '', 98),   -- Staryu
  ('swsh-isle-of-armor', 121, '', 99),   -- Starmie
  ('swsh-isle-of-armor', 891, '', 100),  -- Kubfu
  ('swsh-isle-of-armor', 892, '', 101),  -- Urshifu
  ('swsh-isle-of-armor', 587, '', 102),  -- Emolga
  ('swsh-isle-of-armor', 702, '', 103),  -- Dedenne
  ('swsh-isle-of-armor', 877, '', 104),  -- Morpeko
  ('swsh-isle-of-armor', 81,  '', 105),  -- Magnemite
  ('swsh-isle-of-armor', 82,  '', 106),  -- Magneton
  ('swsh-isle-of-armor', 462, '', 107),  -- Magnezone
  ('swsh-isle-of-armor', 686, '', 108),  -- Inkay
  ('swsh-isle-of-armor', 687, '', 109),  -- Malamar
  ('swsh-isle-of-armor', 746, '', 110),  -- Wishiwashi
  ('swsh-isle-of-armor', 318, '', 111),  -- Carvanha
  ('swsh-isle-of-armor', 319, '', 112),  -- Sharpedo
  ('swsh-isle-of-armor', 506, '', 113),  -- Lillipup
  ('swsh-isle-of-armor', 507, '', 114),  -- Herdier
  ('swsh-isle-of-armor', 508, '', 115),  -- Stoutland
  ('swsh-isle-of-armor', 128, '', 116),  -- Tauros
  ('swsh-isle-of-armor', 241, '', 117),  -- Miltank
  ('swsh-isle-of-armor', 123, '', 118),  -- Scyther
  ('swsh-isle-of-armor', 212, '', 119),  -- Scizor
  ('swsh-isle-of-armor', 127, '', 120),  -- Pinsir
  ('swsh-isle-of-armor', 214, '', 121),  -- Heracross
  ('swsh-isle-of-armor', 557, '', 122),  -- Dwebble
  ('swsh-isle-of-armor', 558, '', 123),  -- Crustle
  ('swsh-isle-of-armor', 767, '', 124),  -- Wimpod
  ('swsh-isle-of-armor', 768, '', 125),  -- Golisopod
  ('swsh-isle-of-armor', 871, '', 126),  -- Pincurchin
  ('swsh-isle-of-armor', 747, '', 127),  -- Mareanie
  ('swsh-isle-of-armor', 748, '', 128),  -- Toxapex
  ('swsh-isle-of-armor', 852, '', 129),  -- Clobbopus
  ('swsh-isle-of-armor', 853, '', 130),  -- Grapploct
  ('swsh-isle-of-armor', 90,  '', 131),  -- Shellder
  ('swsh-isle-of-armor', 91,  '', 132),  -- Cloyster
  ('swsh-isle-of-armor', 769, '', 133),  -- Sandygast
  ('swsh-isle-of-armor', 770, '', 134),  -- Palossand
  ('swsh-isle-of-armor', 425, '', 135),  -- Drifloon
  ('swsh-isle-of-armor', 426, '', 136),  -- Drifblim
  ('swsh-isle-of-armor', 339, '', 137),  -- Barboach
  ('swsh-isle-of-armor', 340, '', 138),  -- Whiscash
  ('swsh-isle-of-armor', 298, '', 139),  -- Azurill
  ('swsh-isle-of-armor', 183, '', 140),  -- Marill
  ('swsh-isle-of-armor', 184, '', 141),  -- Azumarill
  ('swsh-isle-of-armor', 60,  '', 142),  -- Poliwag
  ('swsh-isle-of-armor', 61,  '', 143),  -- Poliwhirl
  ('swsh-isle-of-armor', 62,  '', 144),  -- Poliwrath
  ('swsh-isle-of-armor', 186, '', 145),  -- Politoed
  ('swsh-isle-of-armor', 54,  '', 146),  -- Psyduck
  ('swsh-isle-of-armor', 55,  '', 147),  -- Golduck
  ('swsh-isle-of-armor', 293, '', 148),  -- Whismur
  ('swsh-isle-of-armor', 294, '', 149),  -- Loudred
  ('swsh-isle-of-armor', 295, '', 150),  -- Exploud
  ('swsh-isle-of-armor', 527, '', 151),  -- Woobat
  ('swsh-isle-of-armor', 528, '', 152),  -- Swoobat
  ('swsh-isle-of-armor', 227, '', 153),  -- Skarmory
  ('swsh-isle-of-armor', 524, '', 154),  -- Roggenrola
  ('swsh-isle-of-armor', 525, '', 155),  -- Boldore
  ('swsh-isle-of-armor', 526, '', 156),  -- Gigalith
  ('swsh-isle-of-armor', 744, '', 157),  -- Rockruff
  ('swsh-isle-of-armor', 745, '', 158),  -- Lycanroc
  ('swsh-isle-of-armor', 757, '', 159),  -- Salandit
  ('swsh-isle-of-armor', 758, '', 160),  -- Salazzle
  ('swsh-isle-of-armor', 559, '', 161),  -- Scraggy
  ('swsh-isle-of-armor', 560, '', 162),  -- Scrafty
  ('swsh-isle-of-armor', 619, '', 163),  -- Mienfoo
  ('swsh-isle-of-armor', 620, '', 164),  -- Mienshao
  ('swsh-isle-of-armor', 782, '', 165),  -- Jangmo-o
  ('swsh-isle-of-armor', 783, '', 166),  -- Hakamo-o
  ('swsh-isle-of-armor', 784, '', 167),  -- Kommo-o
  ('swsh-isle-of-armor', 27,  '', 168),  -- Sandshrew
  ('swsh-isle-of-armor', 28,  '', 169),  -- Sandslash
  ('swsh-isle-of-armor', 104, '', 170),  -- Cubone
  ('swsh-isle-of-armor', 105, '', 171),  -- Marowak
  ('swsh-isle-of-armor', 115, '', 172),  -- Kangaskhan
  ('swsh-isle-of-armor', 324, '', 173),  -- Torkoal
  ('swsh-isle-of-armor', 843, '', 174),  -- Silicobra
  ('swsh-isle-of-armor', 844, '', 175),  -- Sandaconda
  ('swsh-isle-of-armor', 551, '', 176),  -- Sandile
  ('swsh-isle-of-armor', 552, '', 177),  -- Krokorok
  ('swsh-isle-of-armor', 553, '', 178),  -- Krookodile
  ('swsh-isle-of-armor', 627, '', 179),  -- Rufflet
  ('swsh-isle-of-armor', 628, '', 180),  -- Braviary
  ('swsh-isle-of-armor', 629, '', 181),  -- Vullaby
  ('swsh-isle-of-armor', 630, '', 182),  -- Mandibuzz
  ('swsh-isle-of-armor', 111, '', 183),  -- Rhyhorn
  ('swsh-isle-of-armor', 112, '', 184),  -- Rhydon
  ('swsh-isle-of-armor', 464, '', 185),  -- Rhyperior
  ('swsh-isle-of-armor', 636, '', 186),  -- Larvesta
  ('swsh-isle-of-armor', 637, '', 187),  -- Volcarona
  ('swsh-isle-of-armor', 170, '', 188),  -- Chinchou
  ('swsh-isle-of-armor', 171, '', 189),  -- Lanturn
  ('swsh-isle-of-armor', 320, '', 190),  -- Wailmer
  ('swsh-isle-of-armor', 321, '', 191),  -- Wailord
  ('swsh-isle-of-armor', 592, '', 192),  -- Frillish
  ('swsh-isle-of-armor', 593, '', 193),  -- Jellicent
  ('swsh-isle-of-armor', 690, '', 194),  -- Skrelp
  ('swsh-isle-of-armor', 691, '', 195),  -- Dragalge
  ('swsh-isle-of-armor', 692, '', 196),  -- Clauncher
  ('swsh-isle-of-armor', 693, '', 197),  -- Clawitzer
  ('swsh-isle-of-armor', 116, '', 198),  -- Horsea
  ('swsh-isle-of-armor', 117, '', 199),  -- Seadra
  ('swsh-isle-of-armor', 230, '', 200),  -- Kingdra
  ('swsh-isle-of-armor', 548, '', 201),  -- Petilil
  ('swsh-isle-of-armor', 549, '', 202),  -- Lilligant
  ('swsh-isle-of-armor', 415, '', 203),  -- Combee
  ('swsh-isle-of-armor', 416, '', 204),  -- Vespiquen
  ('swsh-isle-of-armor', 102, '', 205),  -- Exeggcute
  ('swsh-isle-of-armor', 103, '', 206),  -- Exeggutor
  ('swsh-isle-of-armor', 132, '', 207),  -- Ditto
  ('swsh-isle-of-armor', 137, '', 208),  -- Porygon
  ('swsh-isle-of-armor', 233, '', 209),  -- Porygon2
  ('swsh-isle-of-armor', 474, '', 210),  -- Porygon-Z
  ('swsh-isle-of-armor', 893, '', 211)   -- Zarude
on conflict (game_id, species_id, form_name) do nothing;
