-- Hyperspace Pokédex for Legends: Z-A (Mega Dimension DLC).
-- Source: Serebii.net /legendsz-a/hyperspacepokedex.shtml, verified 2026-05-20.
-- Tracked as legends-za-hyperspace — a DLC sub-dex surfaced as tabs inside the
-- PLZA game page, hidden from the main game catalog.

insert into public.game_dex_entries (game_id, species_id, form_name, entry_number)
values
  ('legends-za-hyperspace', 56,   '', 1),   -- Mankey
  ('legends-za-hyperspace', 57,   '', 2),   -- Primeape
  ('legends-za-hyperspace', 979,  '', 3),   -- Annihilape
  ('legends-za-hyperspace', 52,   '', 4),   -- Meowth
  ('legends-za-hyperspace', 53,   '', 5),   -- Persian
  ('legends-za-hyperspace', 863,  '', 6),   -- Perrserker
  ('legends-za-hyperspace', 83,   '', 7),   -- Farfetch'd
  ('legends-za-hyperspace', 865,  '', 8),   -- Sirfetch'd
  ('legends-za-hyperspace', 104,  '', 9),   -- Cubone
  ('legends-za-hyperspace', 105,  '', 10),  -- Marowak
  ('legends-za-hyperspace', 137,  '', 11),  -- Porygon
  ('legends-za-hyperspace', 233,  '', 12),  -- Porygon2
  ('legends-za-hyperspace', 474,  '', 13),  -- Porygon-Z
  ('legends-za-hyperspace', 921,  '', 14),  -- Capsakid
  ('legends-za-hyperspace', 922,  '', 15),  -- Scovillain
  ('legends-za-hyperspace', 957,  '', 16),  -- Tinkatink
  ('legends-za-hyperspace', 958,  '', 17),  -- Tinkatuff
  ('legends-za-hyperspace', 959,  '', 18),  -- Tinkaton
  ('legends-za-hyperspace', 967,  '', 19),  -- Cyclizar
  ('legends-za-hyperspace', 970,  '', 20),  -- Glimmet
  ('legends-za-hyperspace', 971,  '', 21),  -- Glimmora
  ('legends-za-hyperspace', 479,  '', 22),  -- Rotom
  ('legends-za-hyperspace', 953,  '', 23),  -- Greavard
  ('legends-za-hyperspace', 954,  '', 24),  -- Houndstone
  ('legends-za-hyperspace', 769,  '', 25),  -- Sandygast
  ('legends-za-hyperspace', 770,  '', 26),  -- Palossand
  ('legends-za-hyperspace', 352,  '', 27),  -- Kecleon
  ('legends-za-hyperspace', 973,  '', 28),  -- Flamigo
  ('legends-za-hyperspace', 615,  '', 29),  -- Cryogonal
  ('legends-za-hyperspace', 980,  '', 30),  -- Dondozo
  ('legends-za-hyperspace', 978,  '', 31),  -- Tatsugiri
  ('legends-za-hyperspace', 996,  '', 32),  -- Frigibax
  ('legends-za-hyperspace', 997,  '', 33),  -- Arctibax
  ('legends-za-hyperspace', 998,  '', 34),  -- Baxcalibur
  ('legends-za-hyperspace', 999,  '', 35),  -- Gimmighoul
  ('legends-za-hyperspace', 1000, '', 36),  -- Gholdengo
  ('legends-za-hyperspace', 211,  '', 37),  -- Qwilfish
  ('legends-za-hyperspace', 904,  '', 38),  -- Overqwil
  ('legends-za-hyperspace', 252,  '', 39),  -- Treecko
  ('legends-za-hyperspace', 253,  '', 40),  -- Grovyle
  ('legends-za-hyperspace', 254,  '', 41),  -- Sceptile
  ('legends-za-hyperspace', 255,  '', 42),  -- Torchic
  ('legends-za-hyperspace', 256,  '', 43),  -- Combusken
  ('legends-za-hyperspace', 257,  '', 44),  -- Blaziken
  ('legends-za-hyperspace', 258,  '', 45),  -- Mudkip
  ('legends-za-hyperspace', 259,  '', 46),  -- Marshtomp
  ('legends-za-hyperspace', 260,  '', 47),  -- Swampert
  ('legends-za-hyperspace', 349,  '', 48),  -- Feebas
  ('legends-za-hyperspace', 350,  '', 49),  -- Milotic
  ('legends-za-hyperspace', 433,  '', 50),  -- Chingling
  ('legends-za-hyperspace', 358,  '', 51),  -- Chimecho
  ('legends-za-hyperspace', 876,  '', 52),  -- Indeedee
  ('legends-za-hyperspace', 509,  '', 53),  -- Purrloin
  ('legends-za-hyperspace', 510,  '', 54),  -- Liepard
  ('legends-za-hyperspace', 517,  '', 55),  -- Munna
  ('legends-za-hyperspace', 518,  '', 56),  -- Musharna
  ('legends-za-hyperspace', 538,  '', 57),  -- Throh
  ('legends-za-hyperspace', 539,  '', 58),  -- Sawk
  ('legends-za-hyperspace', 562,  '', 59),  -- Yamask
  ('legends-za-hyperspace', 563,  '', 60),  -- Cofagrigus
  ('legends-za-hyperspace', 867,  '', 61),  -- Runerigus
  ('legends-za-hyperspace', 767,  '', 62),  -- Wimpod
  ('legends-za-hyperspace', 768,  '', 63),  -- Golisopod
  ('legends-za-hyperspace', 827,  '', 64),  -- Nickit
  ('legends-za-hyperspace', 828,  '', 65),  -- Thievul
  ('legends-za-hyperspace', 852,  '', 66),  -- Clobbopus
  ('legends-za-hyperspace', 853,  '', 67),  -- Grapploct
  ('legends-za-hyperspace', 778,  '', 68),  -- Mimikyu
  ('legends-za-hyperspace', 900,  '', 69),  -- Kleavor
  ('legends-za-hyperspace', 877,  '', 70),  -- Morpeko
  ('legends-za-hyperspace', 622,  '', 71),  -- Golett
  ('legends-za-hyperspace', 623,  '', 72),  -- Golurk
  ('legends-za-hyperspace', 821,  '', 73),  -- Rookidee
  ('legends-za-hyperspace', 822,  '', 74),  -- Corvisquire
  ('legends-za-hyperspace', 823,  '', 75),  -- Corviknight
  ('legends-za-hyperspace', 174,  '', 76),  -- Igglybuff
  ('legends-za-hyperspace', 39,   '', 77),  -- Jigglypuff
  ('legends-za-hyperspace', 40,   '', 78),  -- Wigglytuff
  ('legends-za-hyperspace', 926,  '', 79),  -- Fidough
  ('legends-za-hyperspace', 927,  '', 80),  -- Dachsbun
  ('legends-za-hyperspace', 396,  '', 81),  -- Starly
  ('legends-za-hyperspace', 397,  '', 82),  -- Staravia
  ('legends-za-hyperspace', 398,  '', 83),  -- Staraptor
  ('legends-za-hyperspace', 325,  '', 84),  -- Spoink
  ('legends-za-hyperspace', 326,  '', 85),  -- Grumpig
  ('legends-za-hyperspace', 931,  '', 86),  -- Squawkabilly
  ('legends-za-hyperspace', 739,  '', 87),  -- Crabrawler
  ('legends-za-hyperspace', 740,  '', 88),  -- Crabominable
  ('legends-za-hyperspace', 932,  '', 89),  -- Nacli
  ('legends-za-hyperspace', 933,  '', 90),  -- Naclstack
  ('legends-za-hyperspace', 934,  '', 91),  -- Garganacl
  ('legends-za-hyperspace', 316,  '', 92),  -- Gulpin
  ('legends-za-hyperspace', 317,  '', 93),  -- Swalot
  ('legends-za-hyperspace', 41,   '', 94),  -- Zubat
  ('legends-za-hyperspace', 42,   '', 95),  -- Golbat
  ('legends-za-hyperspace', 169,  '', 96),  -- Crobat
  ('legends-za-hyperspace', 935,  '', 97),  -- Charcadet
  ('legends-za-hyperspace', 936,  '', 98),  -- Armarouge
  ('legends-za-hyperspace', 937,  '', 99),  -- Ceruledge
  ('legends-za-hyperspace', 942,  '', 100), -- Maschiff
  ('legends-za-hyperspace', 943,  '', 101), -- Mabosstiff
  ('legends-za-hyperspace', 848,  '', 102), -- Toxel
  ('legends-za-hyperspace', 849,  '', 103), -- Toxtricity
  ('legends-za-hyperspace', 944,  '', 104), -- Shroodle
  ('legends-za-hyperspace', 945,  '', 105), -- Grafaiai
  ('legends-za-hyperspace', 335,  '', 106), -- Zangoose
  ('legends-za-hyperspace', 336,  '', 107), -- Seviper
  ('legends-za-hyperspace', 439,  '', 108), -- Mime Jr.
  ('legends-za-hyperspace', 122,  '', 109), -- Mr. Mime
  ('legends-za-hyperspace', 866,  '', 110), -- Mr. Rime
  ('legends-za-hyperspace', 590,  '', 111), -- Foongus
  ('legends-za-hyperspace', 591,  '', 112), -- Amoonguss
  ('legends-za-hyperspace', 485,  '', 113), -- Heatran
  ('legends-za-hyperspace', 721,  '', 114), -- Volcanion
  ('legends-za-hyperspace', 638,  '', 115), -- Cobalion
  ('legends-za-hyperspace', 639,  '', 116), -- Terrakion
  ('legends-za-hyperspace', 640,  '', 117), -- Virizion
  ('legends-za-hyperspace', 647,  '', 118), -- Keldeo
  ('legends-za-hyperspace', 648,  '', 119), -- Meloetta
  ('legends-za-hyperspace', 649,  '', 120), -- Genesect
  ('legends-za-hyperspace', 720,  '', 121), -- Hoopa
  ('legends-za-hyperspace', 802,  '', 122), -- Marshadow
  ('legends-za-hyperspace', 808,  '', 123), -- Meltan
  ('legends-za-hyperspace', 809,  '', 124), -- Melmetal
  ('legends-za-hyperspace', 491,  '', 125), -- Darkrai
  ('legends-za-hyperspace', 380,  '', 126), -- Latias
  ('legends-za-hyperspace', 381,  '', 127), -- Latios
  ('legends-za-hyperspace', 382,  '', 128), -- Kyogre
  ('legends-za-hyperspace', 383,  '', 129), -- Groudon
  ('legends-za-hyperspace', 384,  '', 130), -- Rayquaza
  ('legends-za-hyperspace', 801,  '', 131), -- Magearna
  ('legends-za-hyperspace', 807,  '', 132)  -- Zeraora
on conflict (game_id, species_id, form_name)
do update set entry_number = excluded.entry_number;
