-- Admin-managed game HOME box form rules.
--
-- This adds:
-- - public.user_profiles: app role storage for auth users
-- - public.is_admin(): helper for RLS policies
-- - public.game_home_box_form_rules: per-game/species/form allow/deny rules
--
-- Bootstrap note:
-- After applying this migration, promote your own account from the SQL editor
-- or with the service role:
--   update public.user_profiles
--   set role = 'admin'
--   where user_id = '<your-auth-user-id>';

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user', 'admin')),
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_user_profiles_role
  on public.user_profiles (role);

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (user_id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', new.email)
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

insert into public.user_profiles (user_id, display_name)
select id, coalesce(raw_user_meta_data ->> 'name', email)
from auth.users
on conflict (user_id) do nothing;

create or replace function public.is_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_profiles
    where user_id = check_user_id
      and role = 'admin'
  );
$$;

create table if not exists public.game_home_box_form_rules (
  id bigint generated by default as identity primary key,
  game_id text not null,
  species_id integer not null references public.species(id) on delete cascade,
  form_name text,
  allowed boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint game_home_box_form_rules_unique unique nulls not distinct (
    game_id,
    species_id,
    form_name
  )
);

create index if not exists ix_game_home_box_form_rules_game_species
  on public.game_home_box_form_rules (game_id, species_id);

create index if not exists ix_game_home_box_form_rules_allowed
  on public.game_home_box_form_rules (allowed);

create or replace function public.set_game_home_box_form_rule_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_game_home_box_form_rules_audit
  on public.game_home_box_form_rules;
create trigger set_game_home_box_form_rules_audit
before insert or update on public.game_home_box_form_rules
for each row execute function public.set_game_home_box_form_rule_audit();

alter table public.user_profiles enable row level security;
alter table public.game_home_box_form_rules enable row level security;

drop policy if exists "Users can read their profile" on public.user_profiles;
create policy "Users can read their profile"
on public.user_profiles for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can create their own user profile" on public.user_profiles;
create policy "Users can create their own user profile"
on public.user_profiles for insert
with check (
  (auth.uid() = user_id and role = 'user')
  or public.is_admin()
);

drop policy if exists "Admins can update profiles" on public.user_profiles;
create policy "Admins can update profiles"
on public.user_profiles for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete profiles" on public.user_profiles;
create policy "Admins can delete profiles"
on public.user_profiles for delete
using (public.is_admin());

drop policy if exists "Game HOME box form rules are readable" on public.game_home_box_form_rules;
create policy "Game HOME box form rules are readable"
on public.game_home_box_form_rules for select
using (true);

drop policy if exists "Admins can insert game HOME box form rules" on public.game_home_box_form_rules;
create policy "Admins can insert game HOME box form rules"
on public.game_home_box_form_rules for insert
with check (public.is_admin());

drop policy if exists "Admins can update game HOME box form rules" on public.game_home_box_form_rules;
create policy "Admins can update game HOME box form rules"
on public.game_home_box_form_rules for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete game HOME box form rules" on public.game_home_box_form_rules;
create policy "Admins can delete game HOME box form rules"
on public.game_home_box_form_rules for delete
using (public.is_admin());

-- Current curated Legends: Z-A rules.
-- Resolver convention for the app:
-- If any rows exist for (game_id, species_id), use only rows where allowed = true.
-- If no rows exist, fall back to the default generated form expansion.
insert into public.game_home_box_form_rules
  (game_id, species_id, form_name, allowed, notes)
values
  -- Pikachu: base/female only; cap forms are event-only.
  ('legends-za', 25, null, true, 'Base Pikachu is obtainable.'),
  ('legends-za', 25, 'pikachu-female', true, 'Female difference is obtainable.'),
  ('legends-za', 25, 'pikachu-original-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-hoenn-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-sinnoh-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-unova-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-kalos-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-alola-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-partner-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),
  ('legends-za', 25, 'pikachu-world-cap', false, 'Cap form is not obtainable from Legends: Z-A.'),

  -- Vivillon: normal, Marine, and Jungle only.
  ('legends-za', 666, null, true, 'Normal Vivillon is obtainable.'),
  ('legends-za', 666, 'vivillon-marine', true, 'Marine pattern is obtainable.'),
  ('legends-za', 666, 'vivillon-jungle', true, 'Jungle pattern is obtainable.'),
  ('legends-za', 666, 'vivillon-polar', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-tundra', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-continental', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-garden', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-elegant', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-meadow', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-modern', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-archipelago', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-high-plains', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-sandstorm', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-river', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-monsoon', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-savanna', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-sun', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-ocean', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-fancy', false, 'Pattern is not obtainable from Legends: Z-A.'),
  ('legends-za', 666, 'vivillon-poke-ball', false, 'Pattern is not obtainable from Legends: Z-A.'),

  -- Other one-off form restrictions.
  ('legends-za', 681, null, true, 'Aegislash Shield/base form is the HOME slot.'),
  ('legends-za', 681, 'aegislash-blade', false, 'Blade Forme is not tracked as a separate HOME slot.'),
  ('legends-za', 713, null, true, 'Standard Avalugg is obtainable.'),
  ('legends-za', 713, 'avalugg-hisui', false, 'Hisuian Avalugg is not obtainable from Legends: Z-A.'),
  ('legends-za', 718, null, true, 'Complete/base Zygarde is the HOME slot.'),
  ('legends-za', 718, 'zygarde-10', false, '10% Forme is not tracked for Legends: Z-A boxes.')
on conflict (game_id, species_id, form_name) do update
set
  allowed = excluded.allowed,
  notes = excluded.notes,
  updated_at = now();
