-- Blueberry Pokédex for Scarlet / Violet: The Indigo Disk DLC.
-- Source: Serebii.net /scarletviolet/blueberrypokedex.shtml, verified 2026-05-30.
-- Tracked as scarlet-violet-indigo-disk — a DLC sub-dex surfaced as tabs inside
-- the Scarlet/Violet game page, hidden from the main game catalog.

insert into public.game_dex_entries (game_id, species_id, form_name, entry_number)
values
  ('scarlet-violet-indigo-disk', 84,   '', 1),   -- Doduo
  ('scarlet-violet-indigo-disk', 85,   '', 2),   -- Dodrio
  ('scarlet-violet-indigo-disk', 102,  '', 3),   -- Exeggcute
  ('scarlet-violet-indigo-disk', 103,  '', 4),   -- Exeggutor
  ('scarlet-violet-indigo-disk', 111,  '', 5),   -- Rhyhorn
  ('scarlet-violet-indigo-disk', 112,  '', 6),   -- Rhydon
  ('scarlet-violet-indigo-disk', 464,  '', 7),   -- Rhyperior
  ('scarlet-violet-indigo-disk', 48,   '', 8),   -- Venonat
  ('scarlet-violet-indigo-disk', 49,   '', 9),   -- Venomoth
  ('scarlet-violet-indigo-disk', 239,  '', 10),  -- Elekid
  ('scarlet-violet-indigo-disk', 125,  '', 11),  -- Electabuzz
  ('scarlet-violet-indigo-disk', 466,  '', 12),  -- Electivire
  ('scarlet-violet-indigo-disk', 240,  '', 13),  -- Magby
  ('scarlet-violet-indigo-disk', 126,  '', 14),  -- Magmar
  ('scarlet-violet-indigo-disk', 467,  '', 15),  -- Magmortar
  ('scarlet-violet-indigo-disk', 440,  '', 16),  -- Happiny
  ('scarlet-violet-indigo-disk', 113,  '', 17),  -- Chansey
  ('scarlet-violet-indigo-disk', 242,  '', 18),  -- Blissey
  ('scarlet-violet-indigo-disk', 123,  '', 19),  -- Scyther
  ('scarlet-violet-indigo-disk', 212,  '', 20),  -- Scizor
  ('scarlet-violet-indigo-disk', 900,  '', 21),  -- Kleavor
  ('scarlet-violet-indigo-disk', 128,  '', 22),  -- Tauros
  ('scarlet-violet-indigo-disk', 522,  '', 23),  -- Blitzle
  ('scarlet-violet-indigo-disk', 523,  '', 24),  -- Zebstrika
  ('scarlet-violet-indigo-disk', 203,  '', 25),  -- Girafarig
  ('scarlet-violet-indigo-disk', 981,  '', 26),  -- Farigiraf
  ('scarlet-violet-indigo-disk', 551,  '', 27),  -- Sandile
  ('scarlet-violet-indigo-disk', 552,  '', 28),  -- Krokorok
  ('scarlet-violet-indigo-disk', 553,  '', 29),  -- Krookodile
  ('scarlet-violet-indigo-disk', 953,  '', 30),  -- Rellor
  ('scarlet-violet-indigo-disk', 954,  '', 31),  -- Rabsca
  ('scarlet-violet-indigo-disk', 627,  '', 32),  -- Rufflet
  ('scarlet-violet-indigo-disk', 628,  '', 33),  -- Braviary
  ('scarlet-violet-indigo-disk', 629,  '', 34),  -- Vullaby
  ('scarlet-violet-indigo-disk', 630,  '', 35),  -- Mandibuzz
  ('scarlet-violet-indigo-disk', 667,  '', 36),  -- Litleo
  ('scarlet-violet-indigo-disk', 668,  '', 37),  -- Pyroar
  ('scarlet-violet-indigo-disk', 585,  '', 38),  -- Deerling
  ('scarlet-violet-indigo-disk', 586,  '', 39),  -- Sawsbuck
  ('scarlet-violet-indigo-disk', 235,  '', 40),  -- Smeargle
  ('scarlet-violet-indigo-disk', 479,  '', 41),  -- Rotom
  ('scarlet-violet-indigo-disk', 868,  '', 42),  -- Milcery
  ('scarlet-violet-indigo-disk', 869,  '', 43),  -- Alcremie
  ('scarlet-violet-indigo-disk', 328,  '', 44),  -- Trapinch
  ('scarlet-violet-indigo-disk', 329,  '', 45),  -- Vibrava
  ('scarlet-violet-indigo-disk', 330,  '', 46),  -- Flygon
  ('scarlet-violet-indigo-disk', 731,  '', 47),  -- Pikipek
  ('scarlet-violet-indigo-disk', 732,  '', 48),  -- Trumbeak
  ('scarlet-violet-indigo-disk', 733,  '', 49),  -- Toucannon
  ('scarlet-violet-indigo-disk', 72,   '', 50),  -- Tentacool
  ('scarlet-violet-indigo-disk', 73,   '', 51),  -- Tentacruel
  ('scarlet-violet-indigo-disk', 116,  '', 52),  -- Horsea
  ('scarlet-violet-indigo-disk', 117,  '', 53),  -- Seadra
  ('scarlet-violet-indigo-disk', 230,  '', 54),  -- Kingdra
  ('scarlet-violet-indigo-disk', 779,  '', 55),  -- Bruxish
  ('scarlet-violet-indigo-disk', 546,  '', 56),  -- Cottonee
  ('scarlet-violet-indigo-disk', 547,  '', 57),  -- Whimsicott
  ('scarlet-violet-indigo-disk', 764,  '', 58),  -- Comfey
  ('scarlet-violet-indigo-disk', 287,  '', 59),  -- Slakoth
  ('scarlet-violet-indigo-disk', 288,  '', 60),  -- Vigoroth
  ('scarlet-violet-indigo-disk', 289,  '', 61),  -- Slaking
  ('scarlet-violet-indigo-disk', 43,   '', 62),  -- Oddish
  ('scarlet-violet-indigo-disk', 44,   '', 63),  -- Gloom
  ('scarlet-violet-indigo-disk', 45,   '', 64),  -- Vileplume
  ('scarlet-violet-indigo-disk', 182,  '', 65),  -- Bellossom
  ('scarlet-violet-indigo-disk', 50,   '', 66),  -- Diglett
  ('scarlet-violet-indigo-disk', 51,   '', 67),  -- Dugtrio
  ('scarlet-violet-indigo-disk', 88,   '', 68),  -- Grimer
  ('scarlet-violet-indigo-disk', 89,   '', 69),  -- Muk
  ('scarlet-violet-indigo-disk', 335,  '', 70),  -- Zangoose
  ('scarlet-violet-indigo-disk', 336,  '', 71),  -- Seviper
  ('scarlet-violet-indigo-disk', 739,  '', 72),  -- Crabrawler
  ('scarlet-violet-indigo-disk', 740,  '', 73),  -- Crabominable
  ('scarlet-violet-indigo-disk', 741,  '', 74),  -- Oricorio
  ('scarlet-violet-indigo-disk', 79,   '', 75),  -- Slowpoke
  ('scarlet-violet-indigo-disk', 80,   '', 76),  -- Slowbro
  ('scarlet-violet-indigo-disk', 199,  '', 77),  -- Slowking
  ('scarlet-violet-indigo-disk', 170,  '', 78),  -- Chinchou
  ('scarlet-violet-indigo-disk', 171,  '', 79),  -- Lanturn
  ('scarlet-violet-indigo-disk', 686,  '', 80),  -- Inkay
  ('scarlet-violet-indigo-disk', 687,  '', 81),  -- Malamar
  ('scarlet-violet-indigo-disk', 370,  '', 82),  -- Luvdisc
  ('scarlet-violet-indigo-disk', 456,  '', 83),  -- Finneon
  ('scarlet-violet-indigo-disk', 457,  '', 84),  -- Lumineon
  ('scarlet-violet-indigo-disk', 594,  '', 85),  -- Alomomola
  ('scarlet-violet-indigo-disk', 324,  '', 86),  -- Torkoal
  ('scarlet-violet-indigo-disk', 661,  '', 87),  -- Fletchling
  ('scarlet-violet-indigo-disk', 662,  '', 88),  -- Fletchinder
  ('scarlet-violet-indigo-disk', 663,  '', 89),  -- Talonflame
  ('scarlet-violet-indigo-disk', 751,  '', 90),  -- Dewpider
  ('scarlet-violet-indigo-disk', 752,  '', 91),  -- Araquanid
  ('scarlet-violet-indigo-disk', 236,  '', 92),  -- Tyrogue
  ('scarlet-violet-indigo-disk', 106,  '', 93),  -- Hitmonlee
  ('scarlet-violet-indigo-disk', 107,  '', 94),  -- Hitmonchan
  ('scarlet-violet-indigo-disk', 237,  '', 95),  -- Hitmontop
  ('scarlet-violet-indigo-disk', 74,   '', 96),  -- Geodude
  ('scarlet-violet-indigo-disk', 75,   '', 97),  -- Graveler
  ('scarlet-violet-indigo-disk', 76,   '', 98),  -- Golem
  ('scarlet-violet-indigo-disk', 529,  '', 99),  -- Drilbur
  ('scarlet-violet-indigo-disk', 530,  '', 100), -- Excadrill
  ('scarlet-violet-indigo-disk', 574,  '', 101), -- Gothita
  ('scarlet-violet-indigo-disk', 575,  '', 102), -- Gothorita
  ('scarlet-violet-indigo-disk', 576,  '', 103), -- Gothitelle
  ('scarlet-violet-indigo-disk', 677,  '', 104), -- Espurr
  ('scarlet-violet-indigo-disk', 678,  '', 105), -- Meowstic
  ('scarlet-violet-indigo-disk', 774,  '', 106), -- Minior
  ('scarlet-violet-indigo-disk', 408,  '', 107), -- Cranidos
  ('scarlet-violet-indigo-disk', 409,  '', 108), -- Rampardos
  ('scarlet-violet-indigo-disk', 410,  '', 109), -- Shieldon
  ('scarlet-violet-indigo-disk', 411,  '', 110), -- Bastiodon
  ('scarlet-violet-indigo-disk', 572,  '', 111), -- Minccino
  ('scarlet-violet-indigo-disk', 573,  '', 112), -- Cinccino
  ('scarlet-violet-indigo-disk', 227,  '', 113), -- Skarmory
  ('scarlet-violet-indigo-disk', 333,  '', 114), -- Swablu
  ('scarlet-violet-indigo-disk', 334,  '', 115), -- Altaria
  ('scarlet-violet-indigo-disk', 81,   '', 116), -- Magnemite
  ('scarlet-violet-indigo-disk', 82,   '', 117), -- Magneton
  ('scarlet-violet-indigo-disk', 462,  '', 118), -- Magnezone
  ('scarlet-violet-indigo-disk', 311,  '', 119), -- Plusle
  ('scarlet-violet-indigo-disk', 312,  '', 120), -- Minun
  ('scarlet-violet-indigo-disk', 559,  '', 121), -- Scraggy
  ('scarlet-violet-indigo-disk', 560,  '', 122), -- Scrafty
  ('scarlet-violet-indigo-disk', 622,  '', 123), -- Golett
  ('scarlet-violet-indigo-disk', 623,  '', 124), -- Golurk
  ('scarlet-violet-indigo-disk', 322,  '', 125), -- Numel
  ('scarlet-violet-indigo-disk', 323,  '', 126), -- Camerupt
  ('scarlet-violet-indigo-disk', 854,  '', 127), -- Sinistea
  ('scarlet-violet-indigo-disk', 855,  '', 128), -- Polteageist
  ('scarlet-violet-indigo-disk', 137,  '', 129), -- Porygon
  ('scarlet-violet-indigo-disk', 233,  '', 130), -- Porygon2
  ('scarlet-violet-indigo-disk', 474,  '', 131), -- Porygon-Z
  ('scarlet-violet-indigo-disk', 595,  '', 132), -- Joltik
  ('scarlet-violet-indigo-disk', 596,  '', 133), -- Galvantula
  ('scarlet-violet-indigo-disk', 602,  '', 134), -- Tynamo
  ('scarlet-violet-indigo-disk', 603,  '', 135), -- Eelektrik
  ('scarlet-violet-indigo-disk', 604,  '', 136), -- Eelektross
  ('scarlet-violet-indigo-disk', 374,  '', 137), -- Beldum
  ('scarlet-violet-indigo-disk', 375,  '', 138), -- Metang
  ('scarlet-violet-indigo-disk', 376,  '', 139), -- Metagross
  ('scarlet-violet-indigo-disk', 610,  '', 140), -- Axew
  ('scarlet-violet-indigo-disk', 611,  '', 141), -- Fraxure
  ('scarlet-violet-indigo-disk', 612,  '', 142), -- Haxorus
  ('scarlet-violet-indigo-disk', 86,   '', 143), -- Seel
  ('scarlet-violet-indigo-disk', 87,   '', 144), -- Dewgong
  ('scarlet-violet-indigo-disk', 131,  '', 145), -- Lapras
  ('scarlet-violet-indigo-disk', 211,  '', 146), -- Qwilfish
  ('scarlet-violet-indigo-disk', 904,  '', 147), -- Overqwil
  ('scarlet-violet-indigo-disk', 577,  '', 148), -- Solosis
  ('scarlet-violet-indigo-disk', 578,  '', 149), -- Duosion
  ('scarlet-violet-indigo-disk', 579,  '', 150), -- Reuniclus
  ('scarlet-violet-indigo-disk', 209,  '', 151), -- Snubbull
  ('scarlet-violet-indigo-disk', 210,  '', 152), -- Granbull
  ('scarlet-violet-indigo-disk', 613,  '', 153), -- Cubchoo
  ('scarlet-violet-indigo-disk', 614,  '', 154), -- Beartic
  ('scarlet-violet-indigo-disk', 27,   '', 155), -- Sandshrew
  ('scarlet-violet-indigo-disk', 28,   '', 156), -- Sandslash
  ('scarlet-violet-indigo-disk', 37,   '', 157), -- Vulpix
  ('scarlet-violet-indigo-disk', 38,   '', 158), -- Ninetales
  ('scarlet-violet-indigo-disk', 459,  '', 159), -- Snover
  ('scarlet-violet-indigo-disk', 460,  '', 160), -- Abomasnow
  ('scarlet-violet-indigo-disk', 884,  '', 161), -- Duraludon
  ('scarlet-violet-indigo-disk', 1018, '', 162), -- Archaludon
  ('scarlet-violet-indigo-disk', 1019, '', 163), -- Hydrapple
  ('scarlet-violet-indigo-disk', 1,    '', 164), -- Bulbasaur
  ('scarlet-violet-indigo-disk', 2,    '', 165), -- Ivysaur
  ('scarlet-violet-indigo-disk', 3,    '', 166), -- Venusaur
  ('scarlet-violet-indigo-disk', 4,    '', 167), -- Charmander
  ('scarlet-violet-indigo-disk', 5,    '', 168), -- Charmeleon
  ('scarlet-violet-indigo-disk', 6,    '', 169), -- Charizard
  ('scarlet-violet-indigo-disk', 7,    '', 170), -- Squirtle
  ('scarlet-violet-indigo-disk', 8,    '', 171), -- Wartortle
  ('scarlet-violet-indigo-disk', 9,    '', 172), -- Blastoise
  ('scarlet-violet-indigo-disk', 152,  '', 173), -- Chikorita
  ('scarlet-violet-indigo-disk', 153,  '', 174), -- Bayleef
  ('scarlet-violet-indigo-disk', 154,  '', 175), -- Meganium
  ('scarlet-violet-indigo-disk', 155,  '', 176), -- Cyndaquil
  ('scarlet-violet-indigo-disk', 156,  '', 177), -- Quilava
  ('scarlet-violet-indigo-disk', 157,  '', 178), -- Typhlosion
  ('scarlet-violet-indigo-disk', 158,  '', 179), -- Totodile
  ('scarlet-violet-indigo-disk', 159,  '', 180), -- Croconaw
  ('scarlet-violet-indigo-disk', 160,  '', 181), -- Feraligatr
  ('scarlet-violet-indigo-disk', 252,  '', 182), -- Treecko
  ('scarlet-violet-indigo-disk', 253,  '', 183), -- Grovyle
  ('scarlet-violet-indigo-disk', 254,  '', 184), -- Sceptile
  ('scarlet-violet-indigo-disk', 255,  '', 185), -- Torchic
  ('scarlet-violet-indigo-disk', 256,  '', 186), -- Combusken
  ('scarlet-violet-indigo-disk', 257,  '', 187), -- Blaziken
  ('scarlet-violet-indigo-disk', 258,  '', 188), -- Mudkip
  ('scarlet-violet-indigo-disk', 259,  '', 189), -- Marshtomp
  ('scarlet-violet-indigo-disk', 260,  '', 190), -- Swampert
  ('scarlet-violet-indigo-disk', 387,  '', 191), -- Turtwig
  ('scarlet-violet-indigo-disk', 388,  '', 192), -- Grotle
  ('scarlet-violet-indigo-disk', 389,  '', 193), -- Torterra
  ('scarlet-violet-indigo-disk', 390,  '', 194), -- Chimchar
  ('scarlet-violet-indigo-disk', 391,  '', 195), -- Monferno
  ('scarlet-violet-indigo-disk', 392,  '', 196), -- Infernape
  ('scarlet-violet-indigo-disk', 393,  '', 197), -- Piplup
  ('scarlet-violet-indigo-disk', 394,  '', 198), -- Prinplup
  ('scarlet-violet-indigo-disk', 395,  '', 199), -- Empoleon
  ('scarlet-violet-indigo-disk', 495,  '', 200), -- Snivy
  ('scarlet-violet-indigo-disk', 496,  '', 201), -- Servine
  ('scarlet-violet-indigo-disk', 497,  '', 202), -- Serperior
  ('scarlet-violet-indigo-disk', 498,  '', 203), -- Tepig
  ('scarlet-violet-indigo-disk', 499,  '', 204), -- Pignite
  ('scarlet-violet-indigo-disk', 500,  '', 205), -- Emboar
  ('scarlet-violet-indigo-disk', 501,  '', 206), -- Oshawott
  ('scarlet-violet-indigo-disk', 502,  '', 207), -- Dewott
  ('scarlet-violet-indigo-disk', 503,  '', 208), -- Samurott
  ('scarlet-violet-indigo-disk', 650,  '', 209), -- Chespin
  ('scarlet-violet-indigo-disk', 651,  '', 210), -- Quilladin
  ('scarlet-violet-indigo-disk', 652,  '', 211), -- Chesnaught
  ('scarlet-violet-indigo-disk', 653,  '', 212), -- Fennekin
  ('scarlet-violet-indigo-disk', 654,  '', 213), -- Braixen
  ('scarlet-violet-indigo-disk', 655,  '', 214), -- Delphox
  ('scarlet-violet-indigo-disk', 656,  '', 215), -- Froakie
  ('scarlet-violet-indigo-disk', 657,  '', 216), -- Frogadier
  ('scarlet-violet-indigo-disk', 658,  '', 217), -- Greninja
  ('scarlet-violet-indigo-disk', 722,  '', 218), -- Rowlet
  ('scarlet-violet-indigo-disk', 723,  '', 219), -- Dartrix
  ('scarlet-violet-indigo-disk', 724,  '', 220), -- Decidueye
  ('scarlet-violet-indigo-disk', 725,  '', 221), -- Litten
  ('scarlet-violet-indigo-disk', 726,  '', 222), -- Torracat
  ('scarlet-violet-indigo-disk', 727,  '', 223), -- Incineroar
  ('scarlet-violet-indigo-disk', 728,  '', 224), -- Popplio
  ('scarlet-violet-indigo-disk', 729,  '', 225), -- Brionne
  ('scarlet-violet-indigo-disk', 730,  '', 226), -- Primarina
  ('scarlet-violet-indigo-disk', 810,  '', 227), -- Grookey
  ('scarlet-violet-indigo-disk', 811,  '', 228), -- Thwackey
  ('scarlet-violet-indigo-disk', 812,  '', 229), -- Rillaboom
  ('scarlet-violet-indigo-disk', 813,  '', 230), -- Scorbunny
  ('scarlet-violet-indigo-disk', 814,  '', 231), -- Raboot
  ('scarlet-violet-indigo-disk', 815,  '', 232), -- Cinderace
  ('scarlet-violet-indigo-disk', 816,  '', 233), -- Sobble
  ('scarlet-violet-indigo-disk', 817,  '', 234), -- Drizzile
  ('scarlet-violet-indigo-disk', 818,  '', 235), -- Inteleon
  ('scarlet-violet-indigo-disk', 1020, '', 236), -- Gouging Fire
  ('scarlet-violet-indigo-disk', 1021, '', 237), -- Raging Bolt
  ('scarlet-violet-indigo-disk', 1023, '', 238), -- Iron Crown
  ('scarlet-violet-indigo-disk', 1022, '', 239), -- Iron Boulder
  ('scarlet-violet-indigo-disk', 1024, '', 240), -- Terapagos
  ('scarlet-violet-indigo-disk', 1009, '', 241), -- Walking Wake
  ('scarlet-violet-indigo-disk', 1010, '', 242), -- Iron Leaves
  ('scarlet-violet-indigo-disk', 1025, '', 243)  -- Pecharunt
on conflict (game_id, species_id, form_name)
do update set entry_number = excluded.entry_number;
